### ISSUE TITLE
Provide a way to test for error responses

### ISSUE THREAD

**Issue by nathany** [swoosh/swoosh#110]
Currently the test adapter always returns `:ok`:
https://github.com/swoosh/swoosh/blob/master/lib/swoosh/adapters/test.ex

It would be nice if there were some way to write mailer tests for the fail case to ensure that errors are handled well.

**Comment by nathany** [comment]
I can write my own adapter for now.

**Comment by nathany** [comment]
Something like this does the trick

```elixir
def deliver(%{to: [{reason, "fail@example.com"}]} = _email, _config) do
  {:error, reason}
end
```

**Comment by stevedomin** [comment]
That's a great suggestion @nathany. Do you think using the `to` field is the best way to go about it?

**Comment by nathany** [comment]
`To` was the easiest to test for me, because the email address can be sent in from higher levels

```elixir
email = {"fail reason", "fail@example.com"}
assert {:error, "fail reason"} = Email.deliver_welcome(email)
```
or
```
user = insert(:user, email: "fail@example.com")
//... do a post in a controller test
```

I'm not totally sure about the error reason though.

Do you think it makes sense to change the test adapter and document the special email address, or just document how to set up a custom adapter?

**Comment by stevedomin** [comment]
I'd definitely like that to be part of the test adapter and document the special email address, I think it would be great to have that built-in.

**Comment by nathany** [comment]
I didn't actually end up using the error reason, so this could be simplified to just have a special email address.
