### ISSUE TITLE
Support inline attachments

### ISSUE THREAD

**Issue by stevedomin** [swoosh/swoosh#122]
We need to had a field to the `Attachment` to set the disposition to either `inline` or `attachment`. We will probably need another `content id` field as well. 

It is supported by some of the providers via their web API. (see `attachments` section of https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html for instance).

**Comment by princemaple** [comment]
for reference #13

**Comment by theodowling** [comment]
Related to pull-request #159
