### ISSUE TITLE
Mailgun 400+ error response has empty body

### ISSUE THREAD

**Issue by princemaple** [swoosh/swoosh#124]
i.e. not JSON-parsable

```elixir
  {:ok, code, _headers, body} when code > 399 ->
    {:error, {code, Poison.decode!(body)}}
```
causes an Poison error

**Comment by stevedomin** [comment]
Is that related to https://github.com/swoosh/swoosh/issues/56 in any way?

**Comment by princemaple** [comment]
Yes. Should we close this in favor of #56 or open multiple issues with every single problem addressed?

**Comment by stevedomin** [comment]
Let's keep these two open for now.

**Comment by DanielDent** [comment]
I got this exception which I suspect is related:

```elixir
** (Jason.DecodeError) unexpected byte at position 0: 0x3C ('<')
    (jason) lib/jason.ex:78: Jason.decode!/2
    (swoosh) lib/swoosh/adapters/mailgun.ex:48: Swoosh.Adapters.Mailgun.deliver/2
```
It's a little ugly from a debugging perspective, because there isn't anything which indicates what error Mailgun gave.

This code seems to be the culprit:
```elixir
      {:ok, code, _headers, body} when code > 399 ->
        {:error, {code, Swoosh.json_library().decode!(body)}}
```

**Comment by princemaple** [comment]
@DanielDent Yeah the error handling is not ideal at the moment. We really need more help from the community to keep up with all the providers.
