### ISSUE TITLE
Module Swoosh.Adapters.SMTP is not available

### ISSUE THREAD

**Issue by doughsay** [swoosh/swoosh#128]
I'm having an odd problem:

```
iex(1)> {:ok, conf} = Application.fetch_env(:email, Email.Mailer)
{:ok,
 [adapter: Swoosh.Adapters.SMTP, relay: {:system, "EMAIL_HOST"},
  username: {:system, "EMAIL_USERNAME"}, password: {:system, "EMAIL_PASSWORD"}]}

iex(2)> Swoosh.Adapters.SMTP.validate_config(conf)
** (UndefinedFunctionError) function Swoosh.Adapters.SMTP.validate_config/1 is undefined (module Swoosh.Adapters.SMTP is not available)
    Swoosh.Adapters.SMTP.validate_config([adapter: Swoosh.Adapters.SMTP, relay: {:system, "EMAIL_HOST"}, username: {:system, "EMAIL_USERNAME"}, password: {:system, "EMAIL_PASSWORD"}])
```

But other adapters are present:

```
iex(3)> conf = [adapter: Swoosh.Adapters.Logger]
[adapter: Swoosh.Adapters.Logger]
iex(4)> Swoosh.Adapters.Logger.validate_config(conf)
:ok
```

Am I doing something really silly here?

**Comment by stevedomin** [comment]
@doughsay sorry that you are running into problem with the library!

Did you add the `gen_smtp` dependency as stated in the installation docs?https://github.com/swoosh/swoosh#installation

The SMTP adapter is conditionally compile only if the `gen_smtp_client` module is loaded, as you can see here: https://github.com/swoosh/swoosh/blob/master/lib/swoosh/adapters/smtp.ex#L1.

Hope that will solve your problem. I'll look into whether we can raise an error when people try to use the module and it's not compiled.

**Comment by doughsay** [comment]
Thanks!  Sorry about not reading the instructions... I had already installed swoosh months ago, and I'm just now switching adapters; forgot to re-check the installation instructions.

**Comment by stevedomin** [comment]
No worries at all @doughsay!

**Comment by vovkats** [comment]
@stevedomin I use elixir 1.5.2 I ran all instructions and got this error

**Comment by stevedomin** [comment]
Hi @vovkats,

https://github.com/swoosh/swoosh/issues/128#issuecomment-302667095 didn't help at all?
