### ISSUE TITLE
Can't customize SMTP port used by SMTP Adapter

### ISSUE THREAD

**Issue by doughsay** [swoosh/swoosh#129]
For local development purposes I'm trying to consolidate all email delivery to a locally running [Mailhog](https://github.com/mailhog/MailHog) instance.  By default it runs its SMTP server on port 1025.  The Swoosh SMTP adapter doesn't seem to be able to customize the port used and always assumes 25.

I looked into how the config is passed to gen_smtp, and it LOOKS like all I need to do is add `port: 1025` to my config and it should theoretically work.  But I haven't been able to get it to work.

Any ideas?

**Comment by princemaple** [comment]
> I looked into how the config is passed to gen_smtp, and it LOOKS like all I need to do is add port: 1025 to my config and it should theoretically work.

That's what I thought, too. Do you have any error logs?

**Comment by valentinewallace** [comment]
Adding the port to my config worked for me, I'm able to get emails. 

Here's my config:
`config :coherence, YourApp.Coherence.Mailer,
  adapter: Swoosh.Adapters.SMTP,
  relay: "smtp.gmail.com",
  port: 587,
  username: [your-username],
  password: [your-password],
  tls: :always,
  auth: :always
`

**Comment by stevedomin** [comment]
@doughsay did you manage to get it working?

**Comment by stevedomin** [comment]
@doughsay if this is still an issue please reopen!

**Comment by Sathras** [comment]
i seem to have the same issue - at least i have a custom port.
using phoenix 1.3 and coherence.
It says email send, no error log; but the email never gets sent.

**Comment by princemaple** [comment]
if you guys want to try out #162
