### ISSUE TITLE
Support attachments

### ISSUE THREAD

**Issue by stevedomin** [swoosh/swoosh#13]
In all the adapters

**Comment by arunvelsriram** [comment]
+1

**Comment by cjhowe** [comment]
It would be nice if this supported Content-ID for embedding images directly into HTML emails.

**Comment by stevedomin** [comment]
@cjhowe definitely something it should do!

**Comment by philipgiuliani** [comment]
+1, would be awesome! :)

**Comment by stevedomin** [comment]
@philipgiuliani at the moment not easily I'm afraid :( I need attachments in one of my personal projects so hopefully this will force me to write it for swoosh soon :)

**Comment by princemaple** [comment]
https://github.com/swoosh/swoosh/pull/119
https://github.com/swoosh/swoosh/pull/121
https://github.com/swoosh/swoosh/pull/123
https://github.com/swoosh/swoosh/pull/125
https://github.com/swoosh/swoosh/pull/126

**Comment by stevedomin** [comment]
This has now landed in master thanks to the great work of @princemaple!
