### ISSUE TITLE
Sending in localhost works but not on the server

### ISSUE THREAD

**Issue by newterminator** [swoosh/swoosh#144]
I am using the SparkPost adaptor with Coherence (which has built in support for Swoosh). The emails are successfully sent from my laptop in development, and I receive them as expected. But using the same config code on the server does not work. I checked the online app logs which is proxy behind nginx and there are no error messages on the app side or nginx side.

I use the ubuntu firewall (ufw) and turned it off and still it does not work. 

Checking the account in SparkPost also shows that the emails are sent from the localhost, but as if SparkPost receives no post request from the server.

Would someone have a clue what could be the issue.

**Comment by princemaple** [comment]
Hi @newterminator ,

I'm afraid we can't help you with that. There are a million possibilities that could have caused this to happen. No reason it works locally but not on server, if you are running with the correct config. Especially when there are no error logs.
The only thing you can do is to add IO.inspect everywhere to check that the app state in every line of your code is indeed what you expect.

**Comment by princemaple** [comment]
This is assuming that you know what you are doing (using the correct env, setting the correct configs in the respecting env, etc)

If you can share your whole project, we might be able to help identify the error.

**Comment by newterminator** [comment]
Hey @princemaple, that was really quick of your response. I really appreciate it. I wont be able to share the whole project code. But if showing the production config file will help perhaps ... 

```elixir
use Mix.Config

config :summarybrew, Summarybrew.Endpoint,
  http: [port: "${PORT}"],
  url: [host: "${HOST}", port: "${PORT}"],
  cache_static_manifest: "priv/static/manifest.json",
  secret_key_base: "${SECRET_KEY_BASE}",
  server: true,
  root: ".",
  version: Mix.Project.config[:version]

# Do not print debug messages in production
config :logger, level: :info

# Configure your database
config :summarybrew, Summarybrew.Repo,
  adapter: Ecto.Adapters.Postgres,
  hostname: "${DB_HOSTNAME}",
  username: "${DB_USERNAME}",
  password: "${DB_PASSWORD}",
  database: "${DB_NAME}",
  pool_size: 20

config :coherence, Summarybrew.Coherence.Mailer,
  adapter: Swoosh.Adapters.SparkPost,
  api_key: "${SPARKPOST_API_KEY}",
  endpoint: "https://api.sparkpost.com/api/v1"
```

Then to start up the app with the proper credentials, I do: 
`REPLACE_OS_VARS=true PORT=4000 HOST=summarybrew.com SECRET_KEY_BASE=kZq... (abbreviated for obvious reasons) ... ./bin/summarybrew start `. 

The app with the forgot password page that sends the email is online here...[summarybrew.com/sessions/new](https://summarybrew.com/sessions/new). 
If you check it out it gives the message as it does in the localhost that it went through, and in the app logs it shows: 
```
iex(summarybrew@127.0.0.1)1> 00:49:41.416 request_id=h6ems64btf7ffopph2g4c7qje49rssk3 [info] GET /passwords/new
00:49:41.419 request_id=h6ems64btf7ffopph2g4c7qje49rssk3 [info] Sent 200 in 3ms
00:49:44.247 request_id=jothel1rqpd67legopkgjd3eaig0e9hr [info] POST /passwords
00:49:44.630 request_id=jothel1rqpd67legopkgjd3eaig0e9hr [info] Sent 302 in 382ms
00:49:45.048 request_id=5lm44mgnilbv4g98n5gjc844s325v91a [info] GET /
00:49:45.091 request_id=5lm44mgnilbv4g98n5gjc844s325v91a [info] Sent 200 in 42ms ^H
```

**Comment by princemaple** [comment]
Ah you are using release. Have you tried removing all the builds and recompile everything, and deploy a new release? @newterminator could be config issue with releases.

**Comment by newterminator** [comment]
Hey @princemaple, yes I did try multiple times with a new release, but to no avail. I tried it to send email from the web server using curl and the SparkPost api key and that worked.

**Comment by princemaple** [comment]
> The only thing you can do is to add IO.inspect everywhere to check that the app state in every line of your code is indeed what you expect.

Have you tried this as well? You have to make sure at least your `Application.get_env` are returning the right values. Testing with curl ensures that your server does have access to the external environment, but does not help with identifying your code path / logic and config correctness.

**Comment by newterminator** [comment]
Hey @princemaple , thank you for being so helpful...I am going to try out your suggestion.

**Comment by princemaple** [comment]
No problem, let me know how that goes. I suspect that you have to use runtime configs (i.e. `{:system, "VAR_NAME"}` in swoosh config plus env vars in your environment for swoosh to work with releases.

**Comment by newterminator** [comment]
It worked your suggestion: as in using `{:system, "VAR_NAME"}` rather than the way I had `api_key: "${SPARKPOST_API_KEY}"`

Wow man, such a small thing, and it drove me bonkers. Multiple new releases I had tried. Thanks so much for saving me. 

Also thank you for writing the SparkPost adaptor for Swoosh. Cheers!

**Comment by princemaple** [comment]
FYI @stevedomin

**Comment by princemaple** [comment]
@newterminator np!
