### ISSUE TITLE
protocol Phoenix.HTML.Safe not implemented for %Swoosh.Email

### ISSUE THREAD

**Issue by max4all** [swoosh/swoosh#152]
I can't use form senders email address on the mail.html page like <%= @email %>. Is there a way to manage this safety setting?

**Comment by princemaple** [comment]
In the context you pass to the view, you can pass whatever information you want. Remember, it's just a Phoenix view.

**Comment by stevedomin** [comment]
Hello @max4all, did @princemaple response helped in solving your issue?

**Comment by yordis** [comment]
@stevedomin 100000% sure that he did what I did long time ago 😆😆😆😆 

@max4all, are you passing `email` as the options to the view?

**Comment by stevedomin** [comment]
@yordis yep, sounds like you're right.

@max4all: does following @yordis suggestion helps with your problem?

**Comment by yordis** [comment]
@stevedomin I would close it, he do not respond, he can always reopen it at any time anyway.

**Comment by psantos10** [comment]
> @stevedomin 100000% sure that he did what I did long time ago 😆😆😆😆
> 
> @max4all, are you passing `email` as the options to the view?
> For example
> 
> ```
> |> render_body("welcome.html", %{email: user.email}) # <--- don't do this
> ```
> 
> You can't pass `email` as some config for the template because `swoosh` used `@email` internally so it will have setup the `%Swoosh.Email{}` instead of your email value

Had the same problem... and the solution was to remove the email option.

Thanks @yordis

**Comment by rogeriochaves** [comment]
hey folks, I've stumbled upon this issue today. I think swoosh shouldn't be this fragile, specially with an error like that where the exception thrown does not help at all, using @email as a variable is common specially if you are doing a contact form email. Should perhaps swoosh use a less common name for its internals?

**Comment by princemaple** [comment]
> hey folks, I've stumbled upon this issue today. I think swoosh shouldn't be this fragile, specially with an error like that where the exception thrown does not help at all, using @email as a variable is common specially if you are doing a contact form email. Should perhaps swoosh use a less common name for its internals?

Unfortunately that'd be a breaking change. Unless hundreds of people complain about it, it probably won't be changed, probably ever. My suggestion is to pass `contact` as a whole and go `@contact.email`.

**Comment by princemaple** [comment]
This issue is more about `phoenix_swoosh` than `swoosh` itself. FYI, `phoenix_swoosh` is about to be deprecated. https://github.com/swoosh/phoenix_swoosh/issues/287
