### ISSUE TITLE
Postmark Custom Headers not sent to API

### ISSUE THREAD

**Issue by esconsut1** [swoosh/swoosh#153]
Hi all,
Thanks for Swoosh.

The Postmark Adapter ignores any custom headers set when composing an email.

new() |> from(...) |> to(...) |> header("foo", "bar")

Looking at the code, I see this part was not completed as yet.

**Comment by stevedomin** [comment]
Hi @esconsut1,

Thanks for the bug report, we'll fix that right away!

**Comment by stevedomin** [comment]
@esconsut1 v0.10 is out with the fix for the Postmark adapter as well as all the other adapters. Again, thanks for reporting!
