### ISSUE TITLE
Emails not sent - SMTP adapter

### ISSUE THREAD

**Issue by Sathras** [swoosh/swoosh#154]
I have problems getting SMTP adapter to work:
i did set my config:
```
defmodule App.Mailer do
  use Swoosh.Mailer,
    otp_app: :swoosh,
    adapter: Swoosh.Adapters.SMTP,
    port: 587,
    relay: {:system, "SMTP_SERVER"},
    username: {:system, "SMTP_EMAIL"},
    password: {:system, "SMTP_PASSWORD"},
    tls: :always,
    auth: :always
end
```
For Testing purposes I do then create a dummy email:

```
# CONTROLLER:
import Swoosh.Email
def index(conn, _params) do
    Task.start(fn ->
      %{name: "Tony Stark", email: "ommited_receiver@gmail.com"}
      |> welcome
      |> IO.inspect
      |> App.Mailer.deliver
    end)

    render conn, "index.html"
end

def welcome(user) do
    new
    |> to({user.name, user.email})
    |> from({"noreply@fuchsberger.us", "ommited_sender@gmail.com"})
    |> subject("Hello, Avengers!")
    |> html_body("<h1>Hello #{user.name}</h1>")
    |> text_body("Hello #{user.name}\n")
end
```
The console output is working well:
```
%Swoosh.Email{assigns: %{}, attachments: [], bcc: [], cc: [],
 from: {"ommited_sender@gmail.com", "ommited_sender@gmail.com"}, headers: %{},
 html_body: "<h1>Hello Tony Stark</h1>", private: %{}, provider_options: %{},
 reply_to: nil, subject: "Hello, Avengers!", text_body: "Hello Tony Stark\n",
 to: [{"Tony Stark", "ommited_receiver@gmail.com"}]}
```
**_But I do never get an email neither an error message in the logger._**

I also noticed that changing my smtp password in the environment variable to a false password results in no change whatsoever.

**Comment by princemaple** [comment]
A few things:

- Your otp app should really be your own app, not swoosh, but this
shouldn't matter here.
- Could you add another IO.inspect below Mailer.deliver?
- Have you tried examing the environment variables in an iex session?

**Comment by Sathras** [comment]
thanks for your feedback.
environment variables are as i believe set up correctly:
response:
```
{:error,
 {:retries_exceeded,
  {:network_failure, 'smtp.world4you.com', {:error, :timeout}}}}
```
the funny thing is, i use the same configuration in gmail to send mails and there it works.

**Comment by princemaple** [comment]
Does it work if you use different ports for Gmail?

**Comment by Sathras** [comment]
i think i am slowly getting to the bottom of this. The issue is that i am trying to use SMPTS through our internal network. I am hosting my production server in from my home network and the provider is not allowing inbound ports. My roommate is a network administrator and we will look over it eventually.

For now i switched to postman adapter which works flawlessly and out of the box.
Thanks for your replys!

**Comment by princemaple** [comment]
Glad you figured it out!
