### ISSUE TITLE
Template and view support

### ISSUE THREAD

**Issue by anthonator** [swoosh/swoosh#160]
Currently, if you want to have view and template support you need to either piggyback off of Phoenix or roll your own. I think it makes sense for Swoosh to provide a mechanism for rendering templates for those of us not using Phoenix.

I could see this being part of Swoosh proper or as a separate package under the Swoosh organization.

The implementation could look similar to Phoenix's template and view implementations. Provide a `Swoosh.Template.Engine` behaviour for template engines to implement against (i.e. `Swoosh.Template.EExEngine`). Also, provide `render`, `render_to_text` and `render_to_html` functions as part of a `Swoosh.View` module or add these to `Swoosh.Email`. If you'd like we can think through the implementation together.

Let me know what you think. I think I can throw this together relatively quickly. If this isn't something Swoosh cares about I can just do this independently. I'd prefer Swoosh to endorse the effort so it can get broader community support.

**Comment by princemaple** [comment]
I think it's a great idea!

Ping @stevedomin

**Comment by stevedomin** [comment]
Hi @anthonator, this is a great idea!

As you said, right now we only piggyback on Phoenix but I wanted to add support for [Smoothie](https://github.com/jfrolich/smoothie) for a long time.

We'd love your contribution on that front. Let me know if I can be of any help.

**Comment by anthonator** [comment]
Great! Excited to get started!

How do you want to do this from an organizational perspective? Do you think it makes sense for this to be part of Swoosh proper or a different library?

Also, I'd like to add a `:template_engines` config. How would you like to do this? We could add it as part of the current mailer config. We could also make it it's own config (this is how Phoenix does it).

An example for the second option:

```elixir
config :swoosh, :template_engines,
  eex: Swoosh.Template.EExEngine
```

**Comment by CrowdHailer** [comment]
Looking through issues as thinking of using swoosh in our project. 

I recently created [eex_html](https://hex.pm/packages/eex_html) (because I don't use phoenix) might be useful if this is still a feature people are working on

**Comment by stevedomin** [comment]
hi @CrowdHailer - this looks great, exactly what we would need for this use case. 👌
