### ISSUE TITLE
Add support for custom attachment headers in all adapters

### ISSUE THREAD

**Issue by stevedomin** [swoosh/swoosh#177]
https://github.com/swoosh/swoosh/pull/176 added support for custom attachment headers in the SMTP adapter (and other adapters depending on `SMTP.Helpers`).

We should add support to all the other adapters when possible. Either way we should indicate in the docs for each adapter whether custom attachment headers are supported or not.

**Comment by princemaple** [comment]
- nothing in sparkpost

**Comment by princemaple** [comment]
Looks like you just have to use smtp if you want more lower level control of the attachments. Leaving these to adapter contributors if they (1) do want this feature  (2) and wants to contribute (3) and the service provider does support it.
