### ISSUE TITLE
Provide Attachment.new for in-memory data

### ISSUE THREAD

**Issue by princemaple** [swoosh/swoosh#181]
Alternatively, separate everything into
- `Attachment.from_plug_conn`
- `Attachment.from_data`
- `Attachment.from_path`

@stevedomin thoughts?

**Comment by stevedomin** [comment]
I like the idea of handling data in `Attachment.new` but I'm not sure how we can differentiate between that and a path, they're both binary no?

**Comment by princemaple** [comment]
We could expand the current functionality with tagged data like `Attachment.new({:data, binary}, opts)`
That being said, I prefer my other options listed above. If needed, add `new` equivalents as well.

**Comment by stevedomin** [comment]
Sounds good!

Should we mark `Attachment.new/1` as deprecated and update the docs to use the functions above?

**Comment by stevedomin** [comment]
We can deprecate in 1.0

**Comment by princemaple** [comment]
Yeah we could. Will be a long journey though :)

**Comment by Doerge** [comment]
#288 works with Mandrill as well 🎉 
```elixir
|> attachment(Attachment.new(
      {:data, binary_data},
      filename: "foobar.pdf",
      content_type: "application/pdf")
    )
```

**Comment by ckruse** [comment]
I started using swoosh and stumbled upon this issue. It looks like the `{:data, binary}` code already exists:

~~~ elixir
  def new({:data, data}, opts) do
    %{struct!(__MODULE__, opts) | data: data}
  end
~~~

And it works like a charm! 👍 Sadly the spec for `new/2` is wrong:

~~~elixir
  @spec new(binary | struct, Keyword.t() | map) :: %__MODULE__{}
~~~

It has to be something like this:

~~~elixir
  @spec new(binary | struct | {:data, binary}, Keyword.t() | map) :: %__MODULE__{}
~~~

**Comment by princemaple** [comment]
Hi @ckruse , would you like to send a PR to correct that? 😃

**Comment by ckruse** [comment]
@princemaple Of course! ✅done: #413

**Comment by princemaple** [comment]
forgot to say thanks @ckruse
