### ISSUE TITLE
Incomplete typespec in Swoosh.Attachment.new

### ISSUE THREAD

**Issue by xadhoom** [swoosh/swoosh#183]
https://github.com/swoosh/swoosh/blob/cee805dc626b2f2e7692c18f5cc72371547ec35a/lib/swoosh/attachment.ex#L28

it should be `@spec new(binary | struct, Keyword.t) :: %__MODULE__{}` since it accepts also a Plug.Upload struct

**Comment by stevedomin** [comment]
@princemaple does it make sense to fix this in https://github.com/swoosh/swoosh/pull/182?

**Comment by princemaple** [comment]
Might as well!
