### ISSUE TITLE
FYI Some Warnings

### ISSUE THREAD

**Issue by jherdman** [swoosh/swoosh#197]
I'm working on a greenfield Elixir 1.6 project, and I noticed the following warnings after installing Swoosh:

```
warning: function :xmerl_scan.string/2 is undefined (module :xmerl_scan is not available)
  lib/swoosh/adapters/xml/helpers.ex:12

warning: function :xmerl_xpath.string/2 is undefined (module :xmerl_xpath is not available)
Found at 2 locations:
  lib/swoosh/adapters/xml/helpers.ex:30
  lib/swoosh/adapters/xml/helpers.ex:38
```

I'm fairly new to Elixir, so my apologies in advance if there's additional context I could have provided. I figured I'd at least open a ticket.

**Comment by stevedomin** [comment]
@jherdman thanks for the heads up.

May I ask which OS you are developing on? I've seen issues where some erlang packages were not installed. See https://chodounsky.net/2015/06/03/elixir-undefined-function-xmerl/.

If that's not the issue I'll keep digging.

**Comment by jherdman** [comment]
macOS High Sierra. I searched around and couldn't find a similar article. I'll keep digging.

**Comment by stevedomin** [comment]
@jherdman apologies for not replying earlier.

I think the issue comes from Swoosh. Can you try pointing swoosh to this branch in your mix.exs file and let me know if you still get these warnings.

```
{:swoosh, github: "swoosh/swoosh", ref: "extra_applications"}
```

Thanks!

**Comment by jherdman** [comment]
Hey Steve! Thanks for the reply. I sheepishly must admit I confused the tabs of my terminal the other day, and confused my developer environments (I do develop on macOS High Sierra, and also on Ubuntu). You were right the first time: I needed to install the erlang-xmerl package. Thank you for looking into this, and my apologies for wasting your time. Keep up the good work, I'm really enjoying this library.

**Comment by stevedomin** [comment]
@jherdman no worries, glad we got it solved! :)

Also glad you're enjoying the library, please ping @princemaple or myself if you run into any issue.
