### ISSUE TITLE
Use xref exclude to suppress undefined module warning and emit explicit warning in validate_config

### ISSUE THREAD

**Issue by princemaple** [swoosh/swoosh#202]
https://github.com/swoosh/swoosh/pull/187#issuecomment-363884842

This way it's probably clearer for users.

cc @stevedomin

**Comment by mikecarroll** [comment]
@princemaple I can take a crack at this this weekend. Only been using Elixir a few days, so may be out of my league, but happy to give it a go, especially given that I reported it.

**Comment by princemaple** [comment]
@mikecarroll sounds great, feel free to ask questions!

**Comment by stevedomin** [comment]
Hi @mikecarroll, hope you are well!

Are you still keen on tackling this one?

**Comment by houmanka** [comment]
No worries, I added Plug and all good. It would be good if you please add this under the MailGun doc :) 

Thanks

**Comment by princemaple** [comment]
@houmanka yep
