### ISSUE TITLE
Switch from Poison to Jason

### ISSUE THREAD

**Issue by princemaple** [swoosh/swoosh#212]

**Comment by Waasi** [comment]
Hello,

Submitted a PR for this. [214](https://github.com/swoosh/swoosh/pull/214)

**Comment by princemaple** [comment]
@Waasi thank you very much for picking up this issue. I've reviewed the PR and left a question. Great job by the way. I could deal with the lock thing myself but am currently out traveling without a work laptop 😅

**Comment by Waasi** [comment]
@princemaple No problem and thanks. I responded. Safe travel! 😄

**Comment by yordis** [comment]
I am curious to know why 🤔. Could you share your experience please

**Comment by princemaple** [comment]
@yordis the community is moving towards Jason. Future Ecto and Phoenix versions are already set to use  Jason.

**Comment by princemaple** [comment]
@Waasi thanks for the contribution
