### ISSUE TITLE
Mailer returns as it was sent but email does not show up Local

### ISSUE THREAD

**Issue by bernardocaputo** [swoosh/swoosh#213]
Swoosh version: 0.8.1 due to dependencies

Hi all, 

I have done everything as the documentation said but apparently the email does not arrive on my localhost:4000

Below you will find my code:
```
# config/dev.exs
config :arvore, Arvore.Mailer,
  adapter: Swoosh.Adapters.Local
```

```
# arvore/mailer/mailer.ex
defmodule Arvore.Mailer do
  use Swoosh.Mailer, otp_app: :arvore
end
```

```
#arvore/mailer/user_email.ex
defmodule Arvore.UserEmail do
  import Swoosh.Email

  def welcome do
    user = %{name: "bernardo", email: "bernardo@teste.com"}
    new
    |> to({user.name, user.email})
    |> from({"Dr B Banner", "hulk.smash@example.com"})
    |> subject("Hello, Avengers!")
    |> html_body("<h1>Hello #{user.name}</h1>")
    |> text_body("Hello #{user.name}\n")
  end
end
```

When I run on iex session:
iex> email = Arvore.UserEmail.welcome
 returns: 
```
%Swoosh.Email{
  assigns: %{},
  attachments: [],
  bcc: [],
  cc: [],
  from: {"Dr B Banner", "hulk.smash@example.com"},
  headers: %{},
  html_body: "<h1>Hello bernardo</h1>",
  private: %{},
  provider_options: %{},
  reply_to: nil,
  subject: "Hello, Avengers!",
  text_body: "Hello bernardo\n",
  to: [{"bernardo", "bernardo@teste.com"}]
}
```
iex> Arvore.Mailer.deliver(email)
returns 
```
{:ok, %{id: "4e0cd845d852b6d69057583b66f84a64"}}
```

but nothing arrives on my mailbox localhost:4000 that was created by running:
```
mix swoosh.mailbox.server
```
<img width="1323" alt="screen shot 2018-03-21 at 11 03 19 pm" src="https://user-images.githubusercontent.com/17001577/37747077-154cd30c-2d5c-11e8-83a5-0606133baa64.png">

Does anybody know how to deal with it? I appreciate it in advance!

**Comment by stevedomin** [comment]
@bernardocaputo did you find out what the problem was?
