### ISSUE TITLE
function Plug.Conn.Query.encode/1 is undefined!!

### ISSUE THREAD

**Issue by houmanka** [swoosh/swoosh#225]
HI guys,

`(UndefinedFunctionError) function Plug.Conn.Query.encode/1 is undefined (module Plug.Conn.Query is not available)`

Thanks

**Comment by princemaple** [comment]
Mailgun requires Plug to work, sorry.

**Comment by princemaple** [comment]
https://github.com/swoosh/swoosh/issues/202
https://github.com/swoosh/swoosh/pull/219
