### ISSUE TITLE
Clearing message queue in mailbox preview

### ISSUE THREAD

**Issue by justanotherdot** [swoosh/swoosh#247]
Is there a way to clear out the mailbox preview for local dev? I would find this useful after long sessions of debugging notifications and don't want to be lost in other emails being sent. 

It looks like `Swoosh.Adapters.Local.Storage.Memory` has a `:delete_all` call implemented. One option I can imagine working for this type of feature.

1. A route to invoke `:delete_all` in `mailbox_preview.ex`
2. A button to simplify invoking the above route

Would this be useful to others? Maybe I'm one of the few that might want this feature.

**Comment by stevedomin** [comment]
We should definitely add a button. I've wanted that myself for a while.

Do you think you can you submit a PR for it?

**Comment by justanotherdot** [comment]
Sure thing 👍

**Comment by princemaple** [comment]
Thanks @justanotherdot !
