### ISSUE TITLE
Copy attachments for dev mailbox

### ISSUE THREAD

**Issue by DanielDent** [swoosh/swoosh#258]
The development mode mock adapter is extremely useful, but currently has a significant limitation: the attached file appears to simply be a pointer to wherever in the filesystem the attachment was located at the time the email was created.

Normal program operation might involve that attachment being deleted immediately after the email is sent, or it might involve a file whose contents change over time. 

Copying the attachment data into a new file would make the dev mock adapter considerably more useful for workflows which involve attachments.

**Comment by princemaple** [comment]
Hi Daniel,

Thanks for reporting!

We could, in this function https://github.com/swoosh/swoosh/blob/master/lib/swoosh/adapters/local/storage/memory.ex#L119-L123
call https://github.com/swoosh/swoosh/blob/master/lib/swoosh/attachment.ex#L78-L80 with :base64
to store the attachments as either provider options or private fields.

Do you feel like you can send a PR?

**Comment by princemaple** [comment]
Closing with #306
