### ISSUE TITLE
Problem with gen_smtp and OTP 21 (matching errors)

### ISSUE THREAD

**Issue by sbrink** [swoosh/swoosh#268]
This is more of help for others because it cost me several hours to figure this.

This current release of `gen_smtp` does not support **OTP 21.**

If you're using Elixir 1.7, you're probably using OTP 21. If this is the case, you'll get matching errors with gen_smtp v0.12. Sth. like cannot match 0A/0B on right side...

Possible solutions:
* Downgrade to OTP 20. It tried this and it solves the problem.
* Use the gen_smtp version from the master branch.

```
{:gen_smtp, github: "Vagabond/gen_smtp", override: true},
```

I would suggest to leave this issue open until a new version of `gen_smtp` is released (> 0.12).

**Comment by princemaple** [comment]
Thank you very much for reporting this. I'll leave this open.

**Comment by princemaple** [comment]
https://github.com/Vagabond/gen_smtp/commit/fc01557777dbae988d919194475d994ff8947628

gen_smtp 0.13 has been released. Could you give it a go?

**Comment by sbrink** [comment]
Not pushed to hex yet: https://hex.pm/packages/gen_smtp

**Comment by princemaple** [comment]
Ah OK, sorry!

**Comment by princemaple** [comment]
Hi @Vagabond sorry about the ping, is there anything holding you back from making a release to hex? Thanks!

**Comment by Vagabond** [comment]
I don't have permissions on hex for gen_smtp (weird I know) and the person who does has not added me.

**Comment by Vagabond** [comment]
I have gained access and I have published 0.13 :)

**Comment by princemaple** [comment]
That's great news!

**Comment by sbrink** [comment]
It works with 0.13. Thx to all :)
