### ISSUE TITLE
Impossible to do partial matching with `Swoosh.TestAssertions.assert_email_not_sent/1`

### ISSUE THREAD

**Issue by 13k** [swoosh/swoosh#274]
`Swoosh.TestAssertions.assert_email_not_sent/1` pins the `email` value and passes it to `refute_received`. Since pattern matching against pinned values compares the actual values instead of doing the pattern match (it's essentially a `==` comparison), it's impossible to use `assert_email_not_sent` with a partial email (like it's possible with `assert_email_sent`). For example:

```elixir
email = Swoosh.Email.new(to: "foo@bar.com")
Swoosh.Adapters.Test.deliver(email, [])

email.to() # => [{"", "foo@bar.com"}]

assert_email_sent(to: "foo@bar.com") # pass
assert_email_not_sent(email) # fail

assert %{to: [{"", "foo@bar.com"}]} = email # pass

assert_email_not_sent(%{to: [{"", "foo@bar.com"}]}) # pass (should fail if actually doing pattern matching)
```

It's possible to allow actual pattern matching if `assert_email_not_sent` is a macro:

```elixir
defmacro assert_email_not_sent(arg) do
  quote do
    refute_received {:email, unquote(arg)}
  end
end
```

Also, shouldn't it be named `refute_email_sent`?

**Comment by princemaple** [comment]
I see what you mean. Do you want to send a PR? I think we can keep the old one and add the refute version. We can then deprecate the old one if necessary.
