### ISSUE TITLE
Templates in Sparkpost

### ISSUE THREAD

**Issue by abderrahmaneayad** [swoosh/swoosh#275]
Is there is a way to use the templates from the [Sparkpost documentation](https://developers.sparkpost.com/api/templates/).

Because this code:
```
def welcome(user) do
  new()
  |> to({user.name, user.email})
  |> put_provider_option(:template_id, "template-email-id")
end
```
does not work.

Am I messing something ?

**Comment by princemaple** [comment]
Hi @abderrahmaneayad ,

You are not missing anything. It's simply not implemented. Please send a PR if you want to use the functionality.
