### ISSUE TITLE
Basic integration testing

### ISSUE THREAD

**Issue by stevedomin** [swoosh/swoosh#28]
It would be good to have some level of integration testing for all the adapters.

**Comment by hubertlepicki** [comment]
@stevedomin I'd gladly take on this. Currently I'm writing integration tests using Hound, and I can't really tell if the message was sent or now.

I think we'd need something similar to ActionMailer in Rails, where the test adapter would store all of the send emails in memory, temporarily, so we can fetch those and check content etc.

In addition to that we'd need some sort of cleaning mechanism, so we can clean the sent out mail between tests.

Does that sound right for

**Comment by stevedomin** [comment]
@hubertlepicki this is actually for having some kind of integration testing for Swoosh itself (PR in progress => https://github.com/swoosh/swoosh/pull/57).

I do want to support what you're suggesting though (ran into this issue myself), I've opened #66 so we can discuss about it. Definitely open to you tackling it!
