### ISSUE TITLE
How to add AWS tags to email?

### ISSUE THREAD

**Issue by OpakAlex** [swoosh/swoosh#282]
Hello, i am tried to add AWS tags to email:
```
  def aws_headers(opts) do
    [
      headers: [
        transactional_type: opts[:type],
        organization: opts[:organization],
        configuration_set_name: "backend"
      ]
    ]
  end
Mailer.deliver(email, headers)
```

But looks like it ignores my tags...

**Comment by princemaple** [comment]
What are they supposed to do? I don't think the feature you are describing is implemented. If you want a specific feature to be implemented, please update your issue to thoroughly describe the feature. Thanks.
