### ISSUE TITLE
How attachment works in Mailgun Adapter.

### ISSUE THREAD

**Issue by ijunaid8989** [swoosh/swoosh#285]
I have tried all available methods such as

`Swoosh.Attachment.new("image base 64 data", type: "inline", filename: "snapshot.jpg", content_type: "image/jpg")`

`%Swoosh.Attachment{data: "image base 64 data", type: "inline", filename: "snapshot.jpg", content_type: "image/jpg"}`

Nothing works, Either I get `[error] :undef` or anyother issue.

If  See the full email object, the base64 data was only there in `path` attribute instead of data?

Can you please tell me I want to use attachment inline with jpeg data, I don't have a file but I have data of that file, which is coming from a live camera.

**Comment by princemaple** [comment]
Indeed mailgun adapter currently doesn't support in-memory attachment. I'll see what I can do.

**Comment by ijunaid8989** [comment]
Until then we need to first save the jpeg and then add it to attachment?

**Comment by ijunaid8989** [comment]
Okay, I have tried to add an attachment as 
```
  defp get_attachments(thumbnail) do
    if thumbnail, do: %Swoosh.Attachment{type: :inline, data: thumbnail, filename: "snapshot.jpg"}, else: nil
  end

  defp add_attachment(email, nil), do: email
  defp add_attachment(email, thumbnail) do
    email |> attachment(Swoosh.Attachment.new(thumbnail, filename: "snapshot.jpg", content_type: "image/jpg", type: "inline"))
  end
```
As according to the code , `get_content` method should work and also give data back if path is not given. right now nothing is happening. May be I am doing something wrong ?

**Comment by princemaple** [comment]
`get_content` works as expected, but is not used in Mailgun adapter code, since Mailgun API is quite different from the rest of the supported providers, apparently I missed the special case when adding inline attachment features to all adapters. We need to make some modifications to Mailgun adapter.

**Comment by ijunaid8989** [comment]
Okay, I am trying to use it in our project github.com/evercam/evercam-server, At first, I started with Bamboo but it don't support inline attachments, So I left it. 

Now I am using swoosh but its supports inline but not the base64 encoded data, I am stuck in these things. Do you think it will be fixed soon? can this part of commit be helpful to you https://github.com/evercam/mailgun/commit/8c73ada08137ce875b487949167d60fecb1715dc

**Comment by ijunaid8989** [comment]
Will it be in the new release? Or should I use GitHub link?

**Comment by ijunaid8989** [comment]
Also I am using Phoenix Swoosh. will that change make it work in phoenix too?

**Comment by princemaple** [comment]
Released in v0.19

Phoenix or not, doesn't matter.

**Comment by princemaple** [comment]
Please pass raw data to Swoosh attachment, not already base64 encoded

**Comment by ijunaid8989** [comment]
Okay, So right now, I am doing this
```
    thumbnail = get_thumbnail(camera)
    new()
    |> from(@from)
    |> to(sharee_email)
    |> bcc(user.email)
    |> add_attachment(thumbnail)
    |> reply_to(user.email)
    |> subject("#{User.get_fullname(user)} has shared the camera #{camera.name} with you.")
    |> render_body("camera_shared_notification.html", %{ user: user, camera: camera, message: message, thumbnail_available: !!thumbnail, year: @year})
    |> IO.inspect
    |> EvercamMedia.Mailer.deliver
```
Attachment is coming in this way

```elixir
  defp add_attachment(email, nil), do: email
  defp add_attachment(email, thumbnail) do
    email |> attachment(Swoosh.Attachment.new(thumbnail, filename: "snapshot.jpg", content_type: "image/jpg", type: "inline"))
  end
```

But on IO.inspect.

I can see attachment like this

```
    year: "2018"
  },
  attachments: [
    %Swoosh.Attachment{
      content_type: "image/jpg",
      data: nil,
      filename: "snapshot.jpg",
      headers: [],
      path: <<255, 216, 255, 224, 0, 16, 74, 70, 73, 70, 0, 1, 2, 0, 0, 1, 0, 1,
        0, 0, 255, 254, 0, 15, 10, 1, 91, 151, 104, 207, 63, 91, 151, 104, 207,
        63, 1, 255, 254, 0, 15, 10, ...>>,
      type: "inline"
    }
  ],
  bcc: [{"", "junaid@evercam.io"}],
  cc: [],
  from: {"", "Evercam <env.dev@evercam.io>"},
  headers: %{},
```
Sorry for commenting again but where Am I wrong this time?

**Comment by princemaple** [comment]
`email |> attachment(Swoosh.Attachment.new({:data, thumbnail}, filename: "snapshot.jpg", content_type: "image/jpeg", type: :inline))`

note: I changed `thumbnail` to `{:data, thumbnail}`, `image/jpg` to `image/jpeg`, `"inline"` to `:inline`

**Comment by ijunaid8989** [comment]
Okay, thanks. Documentation needs improvements.
