### ISSUE TITLE
Add sandbox mode for sendgrid

### ISSUE THREAD

**Issue by rhnonose** [swoosh/swoosh#286]
I would like to have the option to send the e-mail in a sandbox mode, more specifically for sendgrid.

[It's through a field on the payload](https://sendgrid.com/docs/for-developers/sending-email/sandbox-mode/) , but other providers such mailgun and mandrill have a test mode (different api keys).

It could be added as an adapter specific config or as a parameter in the `Email` struct (couldn't find other providers that operate this way but it might be the case).

**Comment by princemaple** [comment]
We have `provider_options` that can be used for provider specific data/operations.
https://github.com/swoosh/swoosh/blob/master/lib/swoosh/email.ex#L32

A few examples:
- https://github.com/swoosh/swoosh/blob/master/lib/swoosh/adapters/mandrill.ex#L165
- https://github.com/swoosh/swoosh/blob/master/lib/swoosh/adapters/sendgrid.ex#L117

You can send a PR to enable sandbox mode for sendgrid adapter.

**Comment by rhnonose** [comment]
Thanks @princemaple, I'll work on it.

**Comment by princemaple** [comment]
Great, thank you!
