### ISSUE TITLE
Add extra headers for SES SendRawEmail

### ISSUE THREAD

**Issue by fdorothy** [swoosh/swoosh#308]
I'm wanting to set the X-SES-SOURCE-ARN, X-SES-FROM-ARN and X-SES-RETURN-PATH-ARN headers when sending an email through SES's SendRawEmail method. See:

https://docs.aws.amazon.com/ses/latest/APIReference/API_SendRawEmail.html

Is it currently possible to set those headers? If not, then it would be nice to be able to specify those headers in the configuration for SES.

**Comment by stevedomin** [comment]
Hello @fdorothy,

We currently don't support setting these headers but it looks like it wouldn't be too hard to add. Do you want to have a crack at it?

**Comment by fdorothy** [comment]
Nevermind, it looks like AWS lets you pass those in as email headers!

**Comment by stevedomin** [comment]
@fdorothy glad you could get it sorted! Have a great day.

**Comment by adamu** [comment]
An option to set `Source` at the API-request level was added in https://github.com/swoosh/swoosh/releases/tag/v1.14.4.
