### ISSUE TITLE
Process.link on :already started memory adapter genserver

### ISSUE THREAD

**Issue by cburman01** [swoosh/swoosh#333]
I have an issue that is probably uncommon: 

When running in a multi node connected environment, swoosh attempts to register global pid:
https://github.com/swoosh/swoosh/blob/master/lib/swoosh/adapters/local/storage/memory.ex#L20

This is fine, but the casefor already_stated links the two pids together. In my cluster, if the linked pid crashes, it will cause the Memory genserver to crash too. Since I am unable to configure the restart strategy because it is being configured in the startup application (Swoosh), I don't have many options. 

Do you have any suggestions? 

My suggestion would be to use a middle module to make the calls to the genserver with the global name instead of having multiple linked genservers. 

Here is a log of the genserver crashing as a result of another node going node: 

>  =SUPERVISOR REPORT==== 21-Jan-2019::13:30:35 ===
> Jan 21 13:30:35 deverlapp02 automationdashboardex[21210]: Supervisor: {local,'Elixir.Swoosh.Supervisor'}
> Jan 21 13:30:35 deverlapp02 automationdashboardex[21210]: Context:    child_terminated
> Jan 21 13:30:35 deverlapp02 automationdashboardex[21210]: Reason:     killed
> Jan 21 13:30:35 deverlapp02 automationdashboardex[21210]: Offender:   [{pid,<0.1553.0>},
> Jan 21 13:30:35 deverlapp02 automationdashboardex[21210]: {id,'Elixir.Swoosh.Adapters.Local.Storage.Memory'},
> Jan 21 13:30:35 deverlapp02 automationdashboardex[21210]: {mfargs,
> Jan 21 13:30:35 deverlapp02 automationdashboardex[21210]: {'Elixir.Swoosh.Adapters.Local.Storage.Memory',
> Jan 21 13:30:35 deverlapp02 automationdashboardex[21210]: start_link,[]}},
> Jan 21 13:30:35 deverlapp02 automationdashboardex[21210]: {restart_type,permanent},
> Jan 21 13:30:35 deverlapp02 automationdashboardex[21210]: {shutdown,5000},
> Jan 21 13:30:35 deverlapp02 automationdashboardex[21210]: {child_type,worker}]

**Comment by princemaple** [comment]
Hi @cburman01 I'm not exactly sure what the problem is. This `Process.link` is supposed to be only called by the supervisor, so the supervisor knows when it's down, and will be able to restart it, across nodes if you were in a cluster and the node used to own this process went down. No other processes should be affected at all.

**Comment by cburman01** [comment]
What I am seeing is if node A goes down, and the process is running on node
a, the process link on node b also crashes and inturn crashes the app. I
don’t see the process being restarted. The whole supervisor crashes on node
b. It’s very odd. I can supply code if we need to discuss more than just
theory.

Collin

**Comment by princemaple** [comment]
Hi again, I just tested spinning up two nodes with swoosh available, joined them together and killed one of them:

Node X
```elixir
> iex.bat --cookie test --sname x -S mix
Interactive Elixir (1.7.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(x@DESKTOP-FIOV8D7)1> GenServer.whereis {:global, Swoosh.Adapters.Local.Storage.Memory}
#PID<0.212.0>
iex(x@DESKTOP-FIOV8D7)2> pid = v()
#PID<0.212.0>
iex(x@DESKTOP-FIOV8D7)3> # Node Y joined
07:57:43.276 [info]  global: Name conflict terminating {Swoosh.Adapters.Local.Storage.Memory, #PID<16395.212.0>}

iex(x@DESKTOP-FIOV8D7)3> GenServer.whereis {:global, Swoosh.Adapters.Local.Storage.Memory}
#PID<0.212.0>
iex(x@DESKTOP-FIOV8D7)4> Terminate batch job (Y/N)?
^C
```

Node Y
```elixir
> iex.bat --cookie test --sname y -S mix
Interactive Elixir (1.7.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(y@DESKTOP-FIOV8D7)1> Node.connect :"x@DESKTOP-FIOV8D7"
true
iex(y@DESKTOP-FIOV8D7)2> GenServer.whereis {:global, Swoosh.Adapters.Local.Storage.Memory}
#PID<16396.212.0>
# killed Node X
iex(y@DESKTOP-FIOV8D7)3> GenServer.whereis {:global, Swoosh.Adapters.Local.Storage.Memory}
#PID<0.224.0>
iex(y@DESKTOP-FIOV8D7)4>
```

Nothing seem to crash, the supervisor on the second node noticed that the global process was down and took over. That's it. Did any other process crash in your scenario?

**Comment by cburman01** [comment]
Tested again and its working. Nothing changed on our end so it must have been something goofy going on. Thanks for your help.
