### ISSUE TITLE
SMTP adapter + html results in long lines in quoted-printable message.

### ISSUE THREAD

**Issue by ivan-kolmychek** [swoosh/swoosh#340]
We are trying to switch our emails to Swoosh from Rails-based system.
We use service to try to predict are our mails counted as spam or not, that includes running them through Barracuda spamfilter.

When we switched, this started to show up in report:
> MIME_QP_LONG_LINE_2 - META: RAW: Quoted-printable line longer than 76 chars

Looking at the quoted-printable source of result, the lines do exceed 76 chars.

As an attempt to quickly fix it, I have locally cloned swoosh and switched encoding of parts to base64 and it looks like that solves the problem.

Does anyone else has this problem?
Would PR with setting to change encodings between quoted-printable and base64 be of any interest to anyone?

**Comment by princemaple** [comment]
released v0.22.0
