### ISSUE TITLE
Amazon SES signing fails

### ISSUE THREAD

**Issue by tv4-infrastruktur** [swoosh/swoosh#344]
When trying the Amazon SES adapter I get a signature error.
Trying the same Amazon SES credentials with the SMTP adapter it works so the error really seems to be related to the signing of the SES request.

```elixir
iex(1)> Swoosh.Email.new() 
|> Swoosh.Email.to({"To Name", "to@mydomain.com"}) 
|> Swoosh.Email.from({"From Name", "from@mydomain.com"}) 
|> Swoosh.Email.subject("Swoosh Email Test") 
|> Swoosh.Email.html_body("<h1>HTML Body</h1>") 
|> Swoosh.Email.text_body("Text Body") 
|> Swoosh.Mailer.deliver(
  adapter: Swoosh.Adapters.AmazonSES, 
  region: "eu-west-1", 
  access_key: "<AWS_ACCESS_KEY>", 
  secret: "<AWS_ACCESS_SECRET>"
)

{:error,
 %{
   code: "SignatureDoesNotMatch",
   message: "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."
 }}
```

**Comment by tv4-infrastruktur** [comment]
Found an issue with the SES access for the AWS credentials.

**Comment by awwong1** [comment]
> Found an issue with the SES access for the AWS credentials.

Hi @tv4-infrastruktur , I am running into this exact same issue and I was wondering what your approach to fixing this was.

```elixir
# works fine
config :app, App.Mailer,
  adapter: Swoosh.Adapters.SMTP,
  relay: "email-smtp.us-west-2.amazonaws.com",
  username: {:system, "AWS_ACCESS_KEY"},
  password: {:system, "AWS_SECRET"},
  tls: :always,
  port: 587

# fails
config :app, App.Mailer
  adapter: Swoosh.Adapters.AmazonSES,
  region: {:system, "AWS_DEFAULT_REGION"},
  access_key: {:system, "AWS_ACCESS_KEY"},
  secret: {:system, "AWS_SECRET"}
```
```text
  %{
   code: "SignatureDoesNotMatch",
   message: "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n'POST\n/\n\ncontent-length:385\ncontent-type:application/x-www-form-urlencoded\nhost:email.us-west-2.amazonaws.com\nx-amz-date:20210627T035545Z\n\ncontent-length;content-type;host;x-amz-date\nff5199a9d705be531e62bf0b3f9c4963ea977458302a2adc8025fb723f7582e4'\n\nThe String-to-Sign should have been\n'AWS4-HMAC-SHA256\n20210627T035545Z\n20210627/us-west-2/ses/aws4_request\n7a13ebc7597ac27064cc305c58382cb47ef8982a2f90508ee6ca3f7a40fff065'\n"
 }
```

**Comment by behe** [comment]
@awwong1 Sorry for late reply, and I hope that you have fixed your issue by now.

I think the problem we had above was that the AWS user associated with the credentials we used did not have the correct access rights to send mail using SES on AWS.

**Comment by awwong1** [comment]
@behe Nothing to apologize for! I am grateful for the response.

> I hope that you have fixed your issue by now.

Currently I am just using the `Swoosh.Adapters.SMTP` adapter. This isn't a blocking issue, but it [would be nice to use the more specific adapter instead of SMTP](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/troubleshoot-throughput-problems.html).

> I think the problem we had above was that the AWS user associated with the credentials we used did not have the correct access rights to send mail using SES on AWS.

I'm not sure that this is an AWS credentials problem, as using the SMTP adapter works without any additional change. Additionally, my user's IAM policy seems is as shown:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "ses:SendRawEmail",
            "Resource": "*"
        }
    ]
}
```
