### ISSUE TITLE
Add validate_config to adapter behaviour

### ISSUE THREAD

**Issue by LostKobrakai** [swoosh/swoosh#345]
It seems that swoosh depends on adapters having `validate_config/1` defined, but it's not part of the behaviour right now. I have an adapter, which is just a thin wrapper around the sparkpost adapter and I don't want to use `use Swoosh.Adapter` as I don't want that to be implemented on my wrapper, but I only want to delegate to `Swoosh.Adapters.Sparkpost`. For cases like that the behaviour should be extended to include `validate_config/1`.

**Comment by princemaple** [comment]
Hi @LostKobrakai what's your reason not wanting to `use Swoosh.Adapter`?
Please take a look at https://github.com/swoosh/swoosh/pull/348, with this PR the adapter module now injects almost no code.

**Comment by LostKobrakai** [comment]
This is twofold. One part is that even if `validate_config/1` is generated it it still should be part of the behaviour if it's required to be implemented. The other part is that I don't want any autogenerated code if I delegate completely to another adapter anyways:

```
defmodule MyApp.Swoosh.SparkpostAdapter do
  @behaviour Swoosh.Adapter

  defdelegate validate_config(config), to: Swoosh.Adapters.SparkPost

  def deliver(email, config) do
    email
    |> Swoosh.Email.put_provider_option(:options, %{
      transactional: true,
      inline_css: true,
      open_tracking: true,
      click_tracking: true
    })
    |> Swoosh.Adapters.SparkPost.deliver(config)
  end
end
```

**Comment by princemaple** [comment]
Makes sense. Updated.

**Comment by princemaple** [comment]
If you get some time, please take another look at #348 
I'll make a release if that looks OK to you.

**Comment by LostKobrakai** [comment]
Looks good to me
