### ISSUE TITLE
Secure handling of access keys

### ISSUE THREAD

**Issue by dottjt** [swoosh/swoosh#361]
I'm just wondering what the recommended way of handling access keys is for both prod and dev.

For example, I'm having to setup Swoosh config in the config file, but I can't dynamically pass in the ENV variables (ACCESS_KEY, SECRET_KEY) because it doesn't work for dev (although works for prod), and obviously I can't put this straight in the file because they need to be committed and they're public.

What is the recommended solution for this? I am also using the Amazon SES module.

Any thoughts appreciated!

**Comment by princemaple** [comment]
Hi @dottjt , for local dev we normally just use `Swoosh.Adapters.Local` which doesn't require any secrets. And for production, indeed using environment variables is the goto way. If you were wondering how to set configs differently for dev and prod, checkout how a phoenix project is generated. If you did want to test it live when developing, every company could have different ways of distributing their dev keys. Most corporate repos are private though, they are fine with simply committing a dev key into the repo.

**Comment by dottjt** [comment]
@princemaple Oh, excellent! Thank you, I think you've lead me in the right direction :)

**Comment by princemaple** [comment]
Glad I could help!
