### ISSUE TITLE
How to implement multiple views in the one file?

### ISSUE THREAD

**Issue by dottjt** [swoosh/swoosh#363]
Hello, I've just got a question.

I've noticed this piece of code at the top of the file, which sets the view and template:

`use Phoenix.Swoosh, view: Sample.EmailView, layout: {Sample.LayoutView, :email}`

However what if I want to use multiple views and layouts in the same file?

Any help is appreciated :)

**Comment by princemaple** [comment]
https://github.com/swoosh/phoenix_swoosh/blob/master/lib/phoenix_swoosh.ex#L54-L59

You could call `put_view` and `put_layout`
