### ISSUE TITLE
Not enforcing password and username to be string with auth: :never

### ISSUE THREAD

**Issue by h4cc** [swoosh/swoosh#364]
We upgraded to v0.22 and got an issue:

When using `Swoosh.Adapters.SMTP` with  `auth: :never` the username and password need to be a string and cant be `nil` because they are checked by `enforce_type!` which fails with:

> ** (ArgumentError) password is not configured properly, got: nil, expected a string

This seemed to introduce that change: https://github.com/swoosh/swoosh/pull/166

**Comment by princemaple** [comment]
Hi, what type are they supposed to be? If `auth: :never` is a valid option, could you send a PR to add it to the list and link the documentation? Thanks.
