### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [swoosh/swoosh#376]
Hello! in my free time I am designing logos for open source software. You can view my portfolio by looking at the activities in my Github profile. I think this project doesn't have a logo. That's why I designed a logo that I think is functional. it represents the function of the software and it also represents elixir. I hope you like this. If you have a different idea, I'd be happy to help. Here is my logo design and logo idea. Best regards.

![swoosh](https://user-images.githubusercontent.com/36298335/55502390-21c0c080-5655-11e9-97b6-8631fcce1fa6.jpg)

**Comment by princemaple** [comment]
@stevedomin 

https://goo.gl/images/3agFLZ this is what it looks like to me... (Bamboo shoot)

**Comment by stevedomin** [comment]
Hi @reallinfo. Thank you very much for offering this. To be completely honest I don' think the project really needs a logo at this point so I'm going to close this. Thanks again for taking the time to do this.
