### ISSUE TITLE
Crashing when set in distributed multi-node environment

### ISSUE THREAD

**Issue by MikaAK** [swoosh/swoosh#401]
We have a 15 node cluster where swoosh is available on a multitude of the nodes, however when one node crashes or there's a few going down and coming up, other nodes that we're testing with (that are literally doing nothing but idling) get crashed by swoosh and taken down which in turn crashes the entire node. 

```elixir
[info] global: Name conflict terminating {Swoosh.Adapters.Local.Storage.Memory, #PID<42923.3171.0>}
[info] global: Name conflict terminating {Swoosh.Adapters.Local.Storage.Memory, #PID<42922.3174.0>}
[info] Application swoosh exited: shutdown
{"Kernel pid terminated",application_controller,"{application_terminated,swoosh,shutdown}"}
Kernel pid terminated (application_controller) ({application_terminated,swoosh,shutdown})
```

We're not using swoosh in any way on the other nodes so I'm going to remove the dependency from there, but never the less this is strange behaviour I wanted to report. 

This is probably related to #333

**Comment by princemaple** [comment]
Midnight in Australia ATM, I'll get to this tomorrow. Feel free to ping me if I forget.

**Comment by MikaAK** [comment]
🙏  no worries

**Comment by princemaple** [comment]
> Is there anyway to provide different names to the `Swoosh.Adapters.Local.Storage.Memory` when clustering nodes?

Nope. There's no point doing it. It's for dev only.

**Comment by princemaple** [comment]
> Thanks. I'll have to figure out how to disable swoosh for certain development and tests.

For specific cases you can disable the local memory process with https://github.com/swoosh/swoosh#production
