### ISSUE TITLE
AmazonSES + Digital Ocean, Ports?

### ISSUE THREAD

**Issue by sensiblearts** [swoosh/swoosh#409]
Sorry to trouble you,

I just moved a working app from GCE to DigitalOcean, and it broke -- cannot send Swoosh emails via SES.

So I opened a ticket at DO.

When they get back to me, **what ports** will I need to tell them to open to let the AmazonSES adapter work properly?

At least, I think it's a firewall issue, per https://www.digitalocean.com/community/questions/digital-ocean-firewall-blocking-sending-email

( Anyone ever encounter this? If true, horrible policy. )

( It worked fine on Google Compute Engine for months, but not after moving to DO. )

Thanks,
David

**Comment by princemaple** [comment]
Hi, the SES adapter does not use any special port. It reaches aws via the http api. My suggestion is to check if there is any error in the log. It could turn out to be an easy configuration error.

**Comment by sensiblearts** [comment]
Thank you! I thought that was the case originally, but when the mails started failing I stumbled on that thread about ports blocked at DigitalOcean.

Did not see any logged errors, but I'll figure it out.
