### ISSUE TITLE
Mailgun support for templates

### ISSUE THREAD

**Issue by steffenix** [swoosh/swoosh#412]
To support mailgun templating, we should add `template`

Reference:
https://documentation.mailgun.com/en/latest/api-sending.html#sending

**Comment by princemaple** [comment]
Hi @steffenix do you think you can send a PR for that? Should be something similar to this https://github.com/swoosh/swoosh/blob/master/lib/swoosh/adapters/mailgun.ex#L100-L110

**Comment by steffenix** [comment]
Yes sure

**Comment by princemaple** [comment]
Thanks @steffenix it's out in 0.24
