### ISSUE TITLE
Sendgrid Adapter

### ISSUE THREAD

**Issue by danielscosta** [swoosh/swoosh#416]
On Sendgrid adapter, its present this code:

`defp prepare_body(email) do
    %{}
    |> prepare_from(email)
    |> prepare_personalizations(email)
    |> prepare_subject(email)
    |> prepare_content(email)
    |> prepare_attachments(email)
    |> prepare_reply_to(email)
    |> prepare_template_id(email)
    |> prepare_categories(email)
    |> prepare_asm(email)
    |> prepare_custom_headers(email)
    |> prepare_mail_settings(email)
  end`

And

`defp prepare_content(body, %{html_body: html, text_body: text}) do
    content =
      cond do
        html && text -> [%{type: "text/plain", value: text}, %{type: "text/html", value: html}]
        html -> [%{type: "text/html", value: html}]
        text -> [%{type: "text/plain", value: text}]
      end
    Map.put(body, :content, content)
  end`

But, if I use template_id functionality, the email content will be present into sendgrid, so, at moment, I wouldn't have a html_body or text_body to input on Map.
If I not put body on Email struct the lib return that error:

`(swoosh) lib/swoosh/adapters/sendgrid.ex:72: Swoosh.Adapters.Sendgrid.prepare_body/1
(swoosh) Swoosh.Adapters.Sendgrid.prepare_content/2
[error] ** (CondClauseError) no cond clause evaluated to a truthy value`

How I should use template_id functionality without broke the lib?

**Comment by princemaple** [comment]
does it error if you put an empty text body `""`?

**Comment by danielscosta** [comment]
Yes, follow:

`{"field" => "content.0.value", "help" => "http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.content.value", "message" => "The content value must be a string at least one character in length."}]}}`

In sendgrid documentation says: 

The content param is required unless you are using a transactional template and have defined a template_ID.

You may not send an email without the content parameter unless you are using a transactional template. This is to prevent you from sending an empty email to your recipients.

I guess if I send a content field into request, so sendgrid ignore template_id.

**Comment by princemaple** [comment]
OK, I have something in mind now. I'll show you some code change tomorrow. You will have to help me test, because I don't use sendgrid :)

**Comment by princemaple** [comment]
Hi @danielscosta @mgiacomini

Just want to get some clarification. What happens when you send both `content` and `template_id` to the API? Does one of them get discarded? Which one does SendGrid actually use? Does it make sense to ever send both of them?

**Comment by danielscosta** [comment]
`template_id` is ignored and SendGrid uses content sended. Not make sense send both because template_id refer a content storaged in SendGrid. SendGrid use both fields, but in different ways and on different requests.  If you app creates a text or html to send by email so you should use content field, but If your text or html was into SendGrid so you should send a template_id which refer him.

**Comment by princemaple** [comment]
Gotcha, so the only problem we are trying to solve here is to allow empty content, correct?

**Comment by danielscosta** [comment]
Yes.
