### ISSUE TITLE
mailgun, string variables should not be jason encoded

### ISSUE THREAD

**Issue by steffenix** [swoosh/swoosh#417]
When using `prepare_custom_vars` a simple string should not be json encoded.

**Comment by steffenix** [comment]
Are you going to release a new version to hex.pm today?

**Comment by princemaple** [comment]
Probably going to wait for #419 so maybe tomorrow. If that's fine with you?

**Comment by steffenix** [comment]
yes

**Comment by princemaple** [comment]
made a release for you
