### ISSUE TITLE
Feature: process html_body with an inliner tool

### ISSUE THREAD

**Issue by augnustin** [swoosh/swoosh#422]
Mail compatibility is hard.

But it can be greatly improved by setting inline styles. Some tool can automate this task:

```
<style>div{color:red;}</style><div/>
<!-- becomes -->
<div style="color: red;"></div>
```

Would there be a plan to integrate such tool in swoosh? 

Haven't found an Elixir library unfortunately, but the JS one could be a source of inspiration https://www.npmjs.com/package/juice.

**Comment by princemaple** [comment]
This can very well be a separate package, given its functionality scope. When there is something we can rely on, we can make it an optional integration, like `Plug`, to have `swoosh` do it automatically. I wouldn't implement it in `swoosh` directly.
