### ISSUE TITLE
Feature: accept markdown body to generate text and html versions

### ISSUE THREAD

**Issue by augnustin** [swoosh/swoosh#423]
Mailing is a lot about content. Hence this should be left editable to product teams. 

As far as I am concerned, I built a system that isolate email contents in markdown format, which subsequently builds the html + text version where:
- HTML version is : HTML layout + markdown content compiled in HTML
- Text version is : raw markdown content

It works well, would be improved with an inliner tool (see #422) but I reckon this could make sense here as a whole feature, wouldn't it?

Cheers

**Comment by princemaple** [comment]
This is much like phoenix_swoosh, and #220, which we never got to finish, and I now think this shouldn't be part of swoosh itself anyway. It's on a different layer of abstraction, or simply a different functionality from what swoosh provides - **sending** email. Both this and #422 can together be a separate package, or even two separate packages, but we have markdown to handle translation already, https://hex.pm/packages/earmark, just need a style inliner.
