### ISSUE TITLE
[Mailjet] get_message_id failed on messages with multiple recipients(TOs)

### ISSUE THREAD

**Issue by chungwong** [swoosh/swoosh#424]
For emails sending to multiple recipients
```elixir
    new()
    |> to([email_a, email_b, email_c])
    |> from({"Dr B Banner", "hulk.smash@example.com"})
    |> subject("Hello, Avengers!")
    |> html_body("<h1>Hello #{user.name}</h1>")
    |> text_body("Hello #{user.name}\n")
```

which Mailjet will return something like this
```elixir
%{
  "Messages" => [
    %{
      "Bcc" => [],
      "Cc" => [],
      "CustomID" => "",
      "Status" => "success",
      "To" => [
        %{
          "Email" => "a@a.com",
          "MessageHref" => "https://api.mailjet.com/v3/REST/message/aaa",
          "MessageID" => aaa,
          "MessageUUID" => "aaaa"
        },
        %{
          "Email" => "b@b.com",
          "MessageHref" => "https://api.mailjet.com/v3/REST/message/bbb",
          "MessageID" => bbb,
          "MessageUUID" => "bbbb"
        },
        %{
          "Email" => "c@c.com",
          "MessageHref" => "https://api.mailjet.com/v3/REST/message/ccc",
          "MessageID" => ccc,
          "MessageUUID" => "cccc"
        }
      ]
    }
  ]
}
```
When [get_message_id/1](https://github.com/swoosh/swoosh/blob/v0.24.2/lib/swoosh/adapters/mailjet.ex#L49), it will throw `(FunctionClauseError) no function clause matching in Swoosh.Adapters.Mailjet.get_message_id/1`

`get_message_id/1` is expecting `To` to contain a list of one element only while there are cases `To` contains multiple elements.

**Comment by princemaple** [comment]
we can add a clause to `get_message_id` to handle the multiple `to` situation, returning a list of message ids, and keeping it backwards compatible (as in single `to` still works the same way)

**Comment by princemaple** [comment]
Now it will return `{:ok, %{id: [...ids...]}}` when there are multiple `to`s
Still returning the singular id, i.e. not a list, when there is only one `to`.

Not great, but it's backwards compatible.
