### ISSUE TITLE
Ran into error following README recommended use of `Task` while trying to also test.

### ISSUE THREAD

**Issue by zorn** [swoosh/swoosh#425]
I'm adding some email to my app and I got it working, even tested with swoosh. Thank you!

Then, because I'm not currently evaluating the mailer response I took the advice of the README and wrapped my internal private mailing function inside of a `Task.start` so I can send the HTTP response quicker and offload the email API call. This however broke my tests. 

If we [look at](https://github.com/swoosh/swoosh/blob/deac88159a0374891f8d0d6b2f71ad46302c281b/lib/swoosh/adapters/test.ex#L23) `Swoosh.Adapters.Test.deliver/2` we can see that it always posts its message to `self()` and in my new scenario this would be the `Task` process (as the README suggested). This results in the process doing the testing never getting the message and thus `assert_email_sent` failing with:

> No message matching {:email, email} after 0ms.

To solve this, maybe I can make a PR that would extend the test version of `deliver` to accept a `config` option for the pid that should accept the `:email` message?

Q: Do other adapters use the `:email` process message or just `Swoosh.Adapters.Test`?

I suppose we could also update the README with a hint of this issue.

New to the project and Elixir so, I welcome corrections and feedback in my assumptions.

**Comment by princemaple** [comment]
Hi Mike, I'm currently traveling. Will be back next week. Will think about this thoroughly then.

Thanks for reporting!

**Comment by princemaple** [comment]
Quick idea though, we can add a provider to the test adapter config, so that it sends the message to a target process, and default to self. Feel free to send a PR if this works. I'll be back on Tuesday Australia Eastern time.

**Comment by princemaple** [comment]
See mailgun or other adapters about provider option.

**Comment by princemaple** [comment]
Hi @zorn 

I ended up using something that's added in Elixir 1.8 to minimize code changes for testing async email delivery. With #427, testing email delivery via `Task.async/start` or their supervised alternatives will simply just work.

**Comment by zorn** [comment]
Thanks so much for your help with this issue!

**Comment by princemaple** [comment]
Hope it works well :)
