### ISSUE TITLE
Feature: batch-send of messages (Mailjet)

### ISSUE THREAD

**Issue by panmichal** [swoosh/swoosh#436]
Some APIs for, for example Mailjet, support sending multiple messages with one request.

https://dev.mailjet.com/email/guides/send-api-v31/#send-a-basic-email - here, `Messages` is an array and the adapter just wraps single email struct in a list to conform with the API.
I could implement handling multiple messages but would like to know your opinion about how it should be handled:
- handling list argument in `delivery/2` https://github.com/swoosh/swoosh/blob/master/lib/swoosh/adapters/mailjet.ex#L34
- separate function - `deliver_many` or something similar

**Comment by princemaple** [comment]
I vote for a separate function, so we can keep the current signature and have clear logic path. Please add an optional callback, deliver_many or batch_deliver, to Adapter and implement it in Mailjet Adapter.

**Comment by panmichal** [comment]
Makes sense! 
I'll work on a PR then.

**Comment by princemaple** [comment]
Thanks! :star2:

**Comment by princemaple** [comment]
I forgot to make a release didn't I?

**Comment by princemaple** [comment]
It's out in 0.25

**Comment by princemaple** [comment]
Thanks for the contribution!
