### ISSUE TITLE
Mailgun: EU sending domain not currently supported

### ISSUE THREAD

**Issue by DavidOliver** [swoosh/swoosh#449]
When using an EU Mailgun sending domain, the endpoint hostname is required to be `api.eu.mailgun.net`.

The endpoint hostname in the adaptor is currently hardcoded as `api.mailgun.net` as a module attribute:

https://github.com/swoosh/swoosh/blob/23fee40fb8bf42f35afd980ce49e645f0b817e9b/lib/swoosh/adapters/mailgun.ex#L37

### References:

- [Mailgun API documentation](https://documentation.mailgun.com/en/latest/api-intro.html#mailgun-regions)
- [Fixing anymail/mailgun "Domain not found" error](https://timonweb.com/posts/fixing-anymailmailgun-domain-not-found-error/)

**Comment by princemaple** [comment]
It's configurable, the module attribute is just a default.

https://github.com/swoosh/swoosh/blob/master/lib/swoosh/adapters/mailgun.ex#L13-L17
https://github.com/swoosh/swoosh/blob/master/lib/swoosh/adapters/mailgun.ex#L62

**Comment by DavidOliver** [comment]
Aha - great! Thanks for the pointers and sorry for the unnecessary issue.

**Comment by princemaple** [comment]
No worries. Have a good day!
