### ISSUE TITLE
Return email body from adapters

### ISSUE THREAD

**Issue by sadir** [swoosh/swoosh#455]
Hi,

I have a use case where we use `Swoosh` to send an email via `Sendgrid`, but then we want to upload the fact that email has been sent into our CRM. They have an API to upload email activity.

This was fine before we used this library because the response from Sendgrid's API has the email that was sent in the `body`. We had built our own `Sendgrid.HTTPClient` and took the details of the email sent from that.`Swoosh` however, does not return the response body.

See: https://github.com/swoosh/swoosh/blob/v0.25.2/lib/swoosh/adapters/sendgrid.ex#L45

I don't want to recreate the email content myself because that's what the dynamic templates are for.

Is there any reason why the Sendgrid adapter is dropping the response body and only returning the message id? Would you consider returning the response body as well?

I've spotted that a decision was made originally to just return the id here: https://github.com/swoosh/swoosh/issues/52

**Comment by princemaple** [comment]
That'd be before I started maintaining this repo. I think we can return more information. Essentially whatever the provider returns. Luckily we are returning a map, we can add the response to it without breaking the current API. Do you feel like putting up a PR?

**Comment by sadir** [comment]
Yeah of course - I'll probably get to it next week at some point but 👍

**Comment by princemaple** [comment]
Looking forward to that. Thanks!

**Comment by sadir** [comment]
Draft PR up to fix this, early feedback welcome.
