### ISSUE TITLE
Revert Sendgrid Adapter body response

### ISSUE THREAD

**Issue by sadir** [swoosh/swoosh#458]
Hey @princemaple.

Really sorry but it looks like I broke your library!

Sendgrid actually don't respond with the message sent. Looking into it they just respond with an empty body.

I had read the docs on that and assumed their docs were incomplete because they don't document the message ID header that you already have in use from what I can see.

https://sendgrid.com/docs/API_Reference/api_v3.html

So it looks like I can't have my original use case of getting the actual email body from the response and using that...

I suppose if you want to stop over-zealous engineers like me from breaking things again you could consider:

- A contract test (record using vcr?) on top of the tests mocking responses you have today.
- A free tier account on adapter providers which you can manually verify against before merging code.

Sorry again and good luck with the library.

**Comment by princemaple** [comment]
We have real integration tests running on master + cron job. There might lack one for sendgrid, I did not know. I'll do the revert tomorrow. It's again mid night in my timezone :facepalm:
