### ISSUE TITLE
optionally passing config as parameter when sending email

### ISSUE THREAD

**Issue by lau** [swoosh/swoosh#46]
Example: Mailgun. It requires you to use the domain you are sending from in API calls. Some sites use more than one domain.

If you have an app that uses several domains, it would be nice if you could pass the domain as part of the parameters to the sending function.

**Comment by barisbalic** [comment]
Hi @lau, thanks for such early feedback!  Is there any reason you would not consider having a mailer for each domain?

**Comment by stevedomin** [comment]
@barisbalic for reference he's the discussion I had with @lau on twitter https://twitter.com/laut/status/712028165523283968

@lau I had another idea, would providing a `Mailer.deliver/2` function help? 1st argument would be the email, and the second would be a keyword list that will be merged with the config passed to the mailer.

```elixir
Mailer.deliver(email, [domain: "mydomain.com"])
```

My thinking is: the more we can avoid coupling `Swoosh.Email` and the provider the better. 

@barisbalic: we could potentially do that but long term I'd like to be a bit more smarter about the way we deal with these and just drop whatever is in that map in the request (that would work really, esp. for the mailgun adapter)

**Comment by barisbalic** [comment]
@stevedomin do what?  Have multiple mailers?

Even though the domain is integral to the request, it could be argued that it is a `provider_option`.  As such you could set it by piping one mail through several functions, each one adding a domain and then sending?

**Comment by stevedomin** [comment]
Not sure I follow you @barisbalic, what do you mean by "each one adding a domain"?

**Comment by barisbalic** [comment]
I meant an alternative to passing all config through, is to make the domain a `provider_option`, such that the following would be possible:

```elixir
email =
  %Swoosh.Email{}
  |> to("someone@somewhere.com")
  |> text_body("Hello")

email
|> from("mailer@website.co.uk")
|> put_provider_option(:domain, "website.co.uk")
|> Mailer.deliver

email
|> from("mailer@website.org")
|> put_provider_option(:domain, "website.org")
|> Mailer.deliver
```

However, given #50 has arisen, I'm pretty certain being able to pass config through as you suggested, makes more sense.

**Comment by lau** [comment]
@barisbalic 

I would prefer to nok make `n` number of mailers, if I can just pass in an option using 1 mailer.

That `provider_option` looks good.

**Comment by barisbalic** [comment]
It's okay, it is slightly different from the intended purpose of `provider_options` though, it is supposed to be reserved for 'additional' provider-specific functionality.  The `domain` is explicitly required, so it feels more like config.  Between that and #50 I think @stevedomin is right about letting people override config with a new `Mailer.deliver/2` function.

**Comment by lau** [comment]
>  letting people override config with a new Mailer.deliver/2 function.

@barisbalic I would also prefer this.

**Comment by stevedomin** [comment]
I started tackling this one, I'm hoping to get it finished sometime this
w-e.
