### ISSUE TITLE
Mail preview, Base path attribute not setting in connection

### ISSUE THREAD

**Issue by iteron-yasir** [swoosh/swoosh#465]
### List mail preview working properly. But viewing a particular email not working.
mix.exs
`{:swoosh, "~> 0.24"}`

dev.exs

```
# Config Local mailer preview
config :application, Mailer, adapter: Swoosh.Adapters.Local

# to change the preview server port (4000 by default)
config :swoosh, serve_mailbox: true, preview_port: 4001
```

router.ex
```
if Mix.env() == :dev do
    pipeline :browser do
      plug :accepts, ["html"]
    end

    scope "/api" do
      pipe_through [:browser]
      forward "/mailbox", Plug.Swoosh.MailboxPreview, base_path: "/api/mailbox"
  end
end
```

It seems base path, still "/". But it want to be "/api/mailbox" I put IO.inspect(conn) in MailboxPreview.to_absolute_url(conn, path)
```
%Plug.Conn{
  adapter: {Plug.Cowboy.Conn, :...},
  assigns: %{
    base_path: "/",
    storage_driver: Swoosh.Adapters.Local.Storage.Memory
  }
```
And, In `MailboxPreview.call(conn, opts)` function opts attribute is getting `[ ]` empty list. From this list base_path was assigned. This list was empty, So, it's not setting the value. Why it's not getting any values. Is I was missing any configuration or router settings ?

**Comment by princemaple** [comment]
I cannot reproduce this. Did you access the page via the path under the same port phoenix is using? Or accessing it via 4001?

**Comment by princemaple** [comment]
![image](https://user-images.githubusercontent.com/1329716/81499388-995c2700-930e-11ea-9d65-e6c71cd66d3d.png)

**Comment by iteron-yasir** [comment]
> I cannot reproduce this. Did you access the page via the path under the same port phoenix is using? Or accessing it via 4001?

I was using port 4001 for mail preview,
```
# Config Local mailer preview
config :application, Mailer, adapter: Swoosh.Adapters.Local

# to change the preview server port (4000 by default)
config :swoosh, serve_mailbox: true, preview_port: 4001
```
I was using docker container for my application. I was not exposed 4001 port outside. From the nginx, I was listening to that API "/api/mailbox" and redirecting to that 4001 port.

When I start the `iex -S mix phx.server`. Mail preview server is starting.
`[info] Running Swoosh mailbox preview server with Cowboy using http on port 4001`

I'am getting list of mails also. But the email view link is not generated based on "base_path"
![Screenshot from 2020-05-10 18-54-05](https://user-images.githubusercontent.com/53789750/81500421-c2b98a80-92ef-11ea-8fc1-5f3d63dffdd1.png)

**Comment by princemaple** [comment]
The 4001 port has no knowledge of the router, hence no base path. You should simply ignore the fact that this port exists, and hit the same origin the Phoenix app listens on, via the path, without having special nginx rewrites.

**Comment by princemaple** [comment]
The port swoosh exposes is for non web apps, e.g. CLI app, to debug mail sending issues.

**Comment by iteron-yasir** [comment]
> The 4001 port has no knowledge of the router, hence no base path. You should simply ignore the fact that this port exists, and hit the same origin the Phoenix app listens on, via the path, without having special nginx rewrites.

@princemaple Thank you very much for the explanation. I got the point.

**Comment by princemaple** [comment]
👍
