### ISSUE TITLE
Runtime accessible config for Gmail Adapter

### ISSUE THREAD

**Issue by akaibukai** [swoosh/swoosh#477]
Hello,
[Here in the docs](https://hexdocs.pm/swoosh/Swoosh.Adapters.Gmail.html#module-required-config-parameters) you define an `:access_token` config parameter.
However in many cases the given OAuth access key is only valid for an hour or so.
How can we provide an updated access token in runtime?

Thank you.

**Comment by princemaple** [comment]
Hi, it can be passed in through the second parameter of deliver function.

**Comment by akaibukai** [comment]
Thanks.
I didn't see it's possible to set it within the deliver function.
