### ISSUE TITLE
Avoiding setting `from` address as Gmail set it for me

### ISSUE THREAD

**Issue by vadimshvetsov** [swoosh/swoosh#489]
Hi.

As [Swoosh.Adapters.Gmail docs](https://hexdocs.pm/swoosh/Swoosh.Adapters.Gmail.html#content) says, I don't need to set `from` and it would be ignored if it wouldn't match account's one.

So this one returns an error:
```ex
%Swoosh.Email{}
|> to({"Me", "my@gmail.com"})
|> subject("Hi")
|> html_body("<div>Hi</div>")
|> ProlingWeb.Mailer.deliver
# {:error, :from_not_set}
```

My umbrella app config:
```ex
config :proling_web, ProlingWeb.Mailer,
  adapter: Swoosh.Adapters.Gmail,
  access_token: {:system, "GMAIL_API_ACCESS_TOKEN"}
```

When I adding a `from` pipe it works:
```ex
%Swoosh.Email{}
|> to({"Me", "my@gmail.com"})
|> from("No reply", "noreply@proling.ru")
# ... the rest
```

What I'm doing wrong or maybe I should fix docs or code in some point?

**Comment by princemaple** [comment]
Hi, Swoosh checks the presence of `from`. We could implement a compile time option to disable the check for Gmail adapter, or simply update the doc...

**Comment by vadimshvetsov** [comment]
@princemaple I suggested am improvement from my point of view, thanks for answering me. I think making check only for Gmail adapter will add complexity.

I'm not sure if this thing could have entire issue but where I can fix encoding for subject and from texts? I'm getting this on my mail :/
![image](https://user-images.githubusercontent.com/16336572/87370142-d9e45500-c58a-11ea-87ed-780fddc1e719.png)

**Comment by princemaple** [comment]
What's your original text encoding? It would be very helpful if you could download the email and somehow share it with me. 
![image](https://user-images.githubusercontent.com/1329716/87370510-724bfb00-c5c6-11ea-8429-2ee3bd30a46e.png)

**Comment by princemaple** [comment]
Also please open a separate issue for the encoding problem for better tracking. Thanks!

**Comment by princemaple** [comment]
And your code that sends this email will be very helpful as well.
