### ISSUE TITLE
Subject, from, to and others API's encoding problem

### ISSUE THREAD

**Issue by vadimshvetsov** [swoosh/swoosh#491]
As I mention in comment https://github.com/swoosh/swoosh/issues/489#issuecomment-657914196, I have a problem with `subject`, `from`, `to` and other API function encoding. When I type anything with Russian - it's turns in gibberish.

I have a template for my mail which works fine and Russian words encoded correctly. But `subject` and `from` is not.

![image](https://user-images.githubusercontent.com/16336572/87475784-0d2bf000-c62e-11ea-84d9-cfca55462d42.png)

Here is downloaded email source [link](https://www.dropbox.com/s/wescivhec693vpp/%C3%90%E2%80%99%C3%90%C2%B0%C3%91%CB%86%C3%90%C2%B0%20%C3%90%C2%B7%C3%90%C2%B0%C3%91%20%C3%90%C2%B2%C3%90%C2%BA%C3%90%C2%B0%20%C3%90%C2%BF%C3%90%C2%BE%C3%90%C2%BB%C3%91%C6%92%C3%91%E2%80%A1%C3%90%C2%B5%C3%90%C2%BD%C3%90%C2%B0.eml?dl=0). Unfortunately github doesn't support uploads with `eml` extension.

Here is my code in umbrella Phoenix app for building this email:

`config/config.exs`
```ex
config :proling_web, ProlingWeb.Mailer,
  adapter: Swoosh.Adapters.Gmail,
  access_token: {:system, "GMAIL_API_ACCESS_TOKEN"}
```
`apps/proling_web/mix.exs`
```ex
  defp deps do
    [
      {:phoenix, "~> 1.5"},
      {:phoenix_pubsub, "~> 2.0"},
      {:phoenix_ecto, "~> 4.0"},
      {:gettext, "~> 0.11"},
      {:proling, in_umbrella: true},
      {:plug_cowboy, "~> 2.3"},
      {:absinthe, "~> 1.5"},
      {:absinthe_plug, "~> 1.5"},
      {:absinthe_phoenix, "~> 2.0"},
      {:poison, "~> 2.1"},
      {:dataloader, "~> 1.0"},
      {:pow, "~> 1.0.20"},
      {:mail, "~> 0.2"},
      {:phoenix_swoosh, "~> 0.2.0"}
    ]
  end
```

`apps/proling_web/lib/proling_web/mailer.ex`
```ex
defmodule ProlingWeb.Mailer do
  use Pow.Phoenix.Mailer
  use Swoosh.Mailer, otp_app: :proling_web

  import Swoosh.Email

  require Logger

  @impl true
  def cast(%{user: user, subject: subject, text: text, html: html}) do
    new()
    |> to({"", user.email})
    |> from({"ProLing", "noreply@proling.ru"})
    |> subject(subject)
    |> html_body(html)
    |> text_body(text)
  end

  @impl true
  def process(email) do
    email
    |> deliver()
    |> log_warnings()
  end

  defp log_warnings({:error, reason}) do
    Logger.warn("Mailer backend failed with: #{inspect(reason)}")
  end

  defp log_warnings({:ok, response}), do: {:ok, response}
end
```

`apps/proling_web/lib/proling_web/emails/request_confirmation.ex`
```ex
defmodule ProlingWeb.RequestConfirmation do
  use Phoenix.Swoosh, view: ProlingWeb.EmailView, layout: {ProlingWeb.LayoutView, :email}

  def request_confirmation(user) do
    new()
    |> from({"Переводческая компания ProLing", "noreply@proling.ru"})
    |> to({"", user.email})
    |> reply_to({"Переводческая компания ProLing", "info@proling.ru"})
    |> subject("Ваша заявка получена")
    |> render_body("request_confirmation.html", %{})
  end
end
```

And I'm using API right now within `iex`:
```ex
ProlingWeb.RequestConfirmation.request_confirmation(%{email: "vadim.shvetsov@gmail.com"}) |> ProlingWeb.Mailer.deliver
```

I'm not sharing templates because they're set properly and there is no problem with body. But if it would be helpful I can share it too.

Let me know how I can help to resolve this issue please.

**Comment by vadimshvetsov** [comment]
I've moved to `Swoosh.Adapters.SMTP` and it works properly with subject, from and to encoding. I think would be more reliable and simple to stick with it.

**Comment by princemaple** [comment]
Hey Vadim,

I'm glad you have found a reliable workaround. However, I'm just curious about if you were testing it on CMD or Powershell on Windows? I did some testing locally and it seems that the shell could be causing the problem. I'm pretty certain that I've tested Chinese with Swoosh before but not with Gmail Adapter, and I've always been using Docker.

If you could show me what you see when using IEx while building the email, it would be of great help.
This is what I see if I use `iex.bat -S mix` instead of running it in Docker.

![image](https://user-images.githubusercontent.com/1329716/87491596-e9979280-c68b-11ea-97ec-99fc0ff610fd.png)

If this was not the cause, my hunch is that `Mail` is not encoding non-ASCII headers properly.

**Comment by vadimshvetsov** [comment]
Hi Po! I've not tested this at Windows or Powershell, I've done it with OS X and Hyper terminal which supports various enconding. I think this problem related to [this issue](https://github.com/DockYard/elixir-mail/issues/78), because `Mail` supports set of certain encodings. That's why `Gmail` adapter works so with Russian characters. Also I can't see any reason to use it instead of SMTP because of handling renew of access tokens. But ofcourse, I can be wrong :)

**Comment by princemaple** [comment]
That's most likely it. Thanks for tracking it down. Too bad `mail` has basically been abandoned now.
