### ISSUE TITLE
Support for Mailgun attributes

### ISSUE THREAD

**Issue by AdamBrodzinski** [swoosh/swoosh#493]
Is there any way to add an attribute of `o:sending-ip` without forking? I see there is support for `o:tags` but this is a bit different. I'm trying to use this attribute to have Mailgun programmatically choose the IP to use based on other criteria.

**Comment by princemaple** [comment]
This will require code change, so a fork is necessary, unfortunately.

**Comment by AdamBrodzinski** [comment]
Ok thanks for the fast follow up! Would you be interested in a PR if I end up forking it?

**Comment by princemaple** [comment]
Of course, PRs are always welcome.

**Comment by princemaple** [comment]
#494 should work for your use case

**Comment by princemaple** [comment]
I'd be great if you could test the branch and let me know whether it works as expected. I don't current use mailgun, so I'm not 100% sure.

**Comment by AdamBrodzinski** [comment]
@princemaple Wow thanks so much for the fast addition there. Looking at the PR it looks like it should work, I'll try it out today or tomorrow and i'll keep you posted 👍
