### ISSUE TITLE
Documentation not up to date for Gmail adapter

### ISSUE THREAD

**Issue by cysiegel** [swoosh/swoosh#499]
Thank you very much for this great library

The documentation in the gmail adapter appears to be outdated (like the atom :system is not in use)      
Also the mail dependency should be listed in the installation guide  (for if using the gmail adapter)

**Comment by princemaple** [comment]
Hey, Gmail adapter seemed pretty OK to me. Anyway, I added explicit code chunk to show the addition of the `mail` dependency.

`{:system, "ENV_VAR"}` should work in all adapters, though.

**Comment by princemaple** [comment]
Please show me some code if it's still not working for you.
