### ISSUE TITLE
Runtime settings

### ISSUE THREAD

**Issue by trinode** [swoosh/swoosh#50]
It seems that at least for the smtp adapter, the env.ex is read once during compilation and those values are compiled in.

Problem being that I'm using System.get_env("SMTP_USERNAME") for example, these values are _not_ available at compile time, but are during runtime (Docker standard behaviour).

This is fine for things like Postgrex and it's database_url setting, or redis configuration, and even mailman - which is what I'm migrating from.

If it's absolutely necessary to keep that behavior for some reason, could there be a deliver method that takes a config (on the mailer and passes that through to the adapter instead of the static configuration)?

**Comment by stevedomin** [comment]
We should definitely support settings these options at runtime, this will be addressed in the upcoming version.

**Comment by lau** [comment]
How about implementing something like what e.g. Phoenix and ex_aws has: You can use for instance: `{:system, "S3_HOST"}` in the config file instead of just a string.

**Comment by stevedomin** [comment]
@lau yes, that sounds like a great idea, I need to look at the actual implementation details

**Comment by stevedomin** [comment]
@trinode @lau this has landed in master and will be part of the 0.2 release

**Comment by stevedomin** [comment]
@trinode 0.2 is available on Hex: https://hex.pm/packages/swoosh
