### ISSUE TITLE
Swoosh.Adapters.Local.Storage.Memory issue in clustered environment

### ISSUE THREAD

**Issue by mszmurlo** [swoosh/swoosh#507]
Hi,

I've integrated Swoosh quickly to my app and I'm using it with SendGrid. Everything was fine until I started to get following messages once I'd added some nodes and formed a cluster:

```
[info] global: Name conflict terminating {Swoosh.Adapters.Local.Storage.Memory, #PID<24159.395.0>}
```

Nodes are started with: `HTTP_PORT=4001 iex --name n1@127.0.0.1 --cookie 123 -S mix phx.server` and `HTTP_PORT=4002 iex --name n2@127.0.0.1 --cookie 123 -S mix phx.server` for the second and the error arises when I join the nodes : `Node.connect(:"n2@127.0.0.1")`. I could not find the text of this error in the source code so I would guess it's about a conflict in some registry where the `pid` of `Swoosh.Adapters.Local.Storage.Memory` is registered. (I'm not using `Swoosh.Adapters.Local.Storage.Memory` and I'm not intending to use it: is there a way to disable it ?)

 Well, maybe it's not an error as it's just an `[info]` message and the system keeps sending mails. Yet, it's a bit annoying... 

Maurycy

**Comment by princemaple** [comment]
Hi Maurycy,

It's a message that's safe to ignore.

However, if you want to get rid of it, add this config:

config :swoosh, local: false

**Comment by princemaple** [comment]
Feel free to reopen if you have further questions

**Comment by mszmurlo** [comment]
That's fine. Thanks for the feedback 

⁣
---
mszmurlo@buguigny.org​

Le 26 août 2020 à 11:23, à 11:23, Po Chen <notifications@github.com> a écrit:
