### ISSUE TITLE
Consider loosening your Poison requirements

### ISSUE THREAD

**Issue by foxnewsnetwork** [swoosh/swoosh#51]
### Proposal
Currently, in `mix.exs`, you have:
```elixir
{:poison, "~> 2.1"}
```
Consider loosening the requirement to also allow version 1.5.x series
```elixir
{:poison, "~> 1.5 or ~> 2.0"}
```

### Why?
After a casual search for Poison in the swoosh codebase:

https://github.com/swoosh/swoosh/search?utf8=%E2%9C%93&q=Poison

I noticed that swoosh uses neither the `defimpl` feature of the `1.5.x` poison nor the `@derive Poison.Encoder` of the `2.x` series to define it's encoding rules, preferring instead to leave the dirty work to Poison itself. 

This means swoosh can probably support both versions of poison, which means, for us pleb end-users, if you could loosen your poison requirement, it would make things a lot easier as a lot of our older libraries depend on the 1.x series of poison.

**Comment by barisbalic** [comment]
Hey @foxnewsnetwork thank you ever so much for such a detailed piece of feedback, it is greatly appreciated.  Something I have been wondering about was whether we should actually have `Poison` as a dependancy at all, or instead allow users to specify the JSON library they would prefer to use.

One way or another we'll definitely loosen the requirement, I'll leave this open until @stevedomin drops some input on the thread!

**Comment by stevedomin** [comment]
Thanks for the report @foxnewsnetwork, we can definitely lower the requirement

**Comment by stevedomin** [comment]
Fixed in master (https://github.com/swoosh/swoosh/commit/76283910d85714866bd0c776e432284cc1ec5e36)

Thanks again for reporting this issue, I think a lot of people will probably run into it!

**Comment by barisbalic** [comment]
No specific forts on dropping the dep altogether?

**Comment by stevedomin** [comment]
My feeling is that since the result of encoding/decoding isn't exposed in any way to the end user of the library it doesn't really matter which one we use for now.
