### ISSUE TITLE
How to specify a text layout?

### ISSUE THREAD

**Issue by GildedHonour** [swoosh/swoosh#510]
How to specify a **text** layout for an email?

**Comment by princemaple** [comment]
https://hexdocs.pm/phoenix_swoosh/Phoenix.Swoosh.html?#module-example
https://hexdocs.pm/phoenix_swoosh/Phoenix.Swoosh.html?#put_layout/2

just change `.html` to `.txt`, or use an atom if you want it to be picked up automatically.
