### ISSUE TITLE
Adapter return value

### ISSUE THREAD

**Issue by bismark** [swoosh/swoosh#52]
The Adapter behaviour's function signature allows of a successful return type as `:ok | {:ok, term}` with no  indication of why one or the other. This makes pattern matching a bit cumbersome without knowing the internals of the adapter.

Is there a reason why both are supported? Can this be documented more clearly?

**Comment by barisbalic** [comment]
Hey @bismark, originally we felt there was probably no need to return anything on a successful "send", but after working with the services, it looks like most services will return a unique ID for the email, so we'll probably refactor success responses all to be in the form of `{:atom, term}`, thanks for making us think about it, I'll leave this open until the refactoring is done.

**Comment by stevedomin** [comment]
@bismark: fyi @barisbalic put a PR in this week-end that addresses this behaviour => https://github.com/swoosh/swoosh/pull/53

**Comment by barisbalic** [comment]
Hey @bismark, all adapters should now have a uniform return value.

**Comment by stevedomin** [comment]
(In the upcoming 0.2 release)

**Comment by stevedomin** [comment]
0.2 is available on Hex: https://hex.pm/packages/swoosh
