### ISSUE TITLE
Add support for Postmark's new broadcast email stream option.

### ISSUE THREAD

**Issue by zorn** [swoosh/swoosh#523]
https://postmarkapp.com/videos/introducing-broadcast-message-streams

I've started work on this. You can check out my early progress here:

https://github.com/Guildflow/swoosh/commits/postmark-updates

Once I finish more testing I'll make a PR. I just wanted to post an issue here in case anyone is looking for these additions in the mean time.

**Comment by princemaple** [comment]
Thanks. You can also send a draft PR, BTW.

**Comment by princemaple** [comment]
Code on your branch looking promising!
