### ISSUE TITLE
Document various provider options

### ISSUE THREAD

**Issue by princemaple** [swoosh/swoosh#525]
Many provider options are hidden in code.

They need to be documented in the adapter module doc.

Helps are appreciated!

**Comment by kianmeng** [comment]
@princemaple Something like `Swoosh.Adapters.Postmark` (shown below) for other adapters or we need even more elaboration for each options?

```
 51   ## Provider Options
 52 
 53   - `:metadata` (map)
 54   - `:tag` (string)
 55   - `:template_id` (string)
 56   - `:template_alias` (string)
 57   - `:template_model` (map)
```

**Comment by princemaple** [comment]
@kianmeng similar list would suffice for visibility. Most users of their respective adapter would already know what they are for. Plus all adapters have their provider doc linked.

**Comment by kianmeng** [comment]
TODO:

- [ ] AmazonSES - https://github.com/swoosh/swoosh/pull/638
- [ ] Dyn
- [ ] Gmail
- [ ] Local
- [ ] Logger
- [ ] Mailgun
- [ ] Mailjet
- [ ] Mandrill
- [ ] Postmark
- [ ] Sendgrid
- [ ] SendInBlue
- [ ] Sendmail
- [ ] SMTP
- [ ] SocketLabs
- [ ] Sparkpost
- [ ] Test

**Comment by kianmeng** [comment]
@princemaple Are they any adapters currently missing? If not, then we can close this ticket.

**Comment by princemaple** [comment]
Thank you very much for your PRs :)
