### ISSUE TITLE
Mailer with defoverridable

### ISSUE THREAD

**Issue by danielscosta** [swoosh/swoosh#536]
```
defmacro __using__(opts) do
    quote bind_quoted: [opts: opts] do
      alias Swoosh.Mailer

      @otp_app Keyword.fetch!(opts, :otp_app)
      @mailer_config opts

      @spec deliver(Swoosh.Email.t(), Keyword.t()) :: {:ok, term} | {:error, term}
      def deliver(email, config \\ [])

      def deliver(email, config) do
        Mailer.deliver(email, parse_config(config))
      end

      defoverridable deliver: 2
...
```

It is possible?

**Comment by princemaple** [comment]
There is no point doing this. You can simply define a different function that wraps `deliver`, call it `wrapped_deliver` or whatever. And use that function in your own codebase.

**Comment by princemaple** [comment]
If you really like the name "deliver", you can name the module that contains "use" "DefaultMailer" and define a different module that defines your own "deliver" that does your extra things and call DefaultMailer.deliver when necessary.
