### ISSUE TITLE
Make `from` optional

### ISSUE THREAD

**Issue by tofran** [swoosh/swoosh#537]
Hello, thank you for the great work.

# Context:

We are creating an adapter for [Sendingblue](https://www.sendinblue.com/).
In Sendingblue if you do not specify `from` in the API request, it will delegate this to whats configured in the template editor (on their platform).

# Problem:

Currently `lib/swoosh/mailer.ex` prevents empty `from` addresses:

```
def deliver(%Swoosh.Email{from: nil}, _config) do
    {:error, :from_not_set}
  end
  def deliver(%Swoosh.Email{from: {_name, address}}, _config)
      when address in ["", nil] do
    {:error, :from_not_set}
  end
```

And we get the error: `{:error, :from_not_set}`

# Question:

What is the best way to make `from` optional?
How would you do it for our use case? (Without ugly hacks)
If we want to contribute our adapter to this repo how can we integrate this feature in your codebase?

Many thanks in advance.

EDIT: improved wording

**Comment by princemaple** [comment]
Instead of allowing empty `from`, I might expand the current implementation to accept atoms. And in your adapter code you could look for a specific atom that denotes the intention to use the configured value, and then ignore it.

**Comment by tofran** [comment]
@princemaple this would involve a refactor in your API, right?
Meaning you would have to update existing adapters?

**Comment by princemaple** [comment]
Not really. It would just be an addition. Existing adapters don't necessarily need to handle atom `from`. Most changes will be in email.ex, nailer.ex and format.ex

**Comment by princemaple** [comment]
Let me know if you need any help.

**Comment by princemaple** [comment]
Thanks for the contribution @tofran . The new adapter is released in v1.2.0. The task to remove enforced `from` field is tracked in #556 as a future breaking change.

**Comment by tofran** [comment]
Very good point, Sendinblue actually rejects empty subject:

```json
{
  "code": "missing_parameter",
  "message": "subject is required"
}
```

So case closed, theres no problem with the current implementation

**Comment by princemaple** [comment]
@tofran thanks for the confirmation!
