### ISSUE TITLE
gen_smtp 1.0 does not seem to be working 

### ISSUE THREAD

**Issue by gabrielrinaldi** [swoosh/swoosh#552]
I tried to upgrade to the latest version of swoosh (1.1.1) and gen_smtp (1.0) and while it seems that swoosh now supports gen_smtp 1.0 I still get an error:
```
* (BadMapError) expected a map, got: [{"content-type-params", [{"charset", "utf-8"}]}, {"disposition", "inline"}, {"disposition-params", []}]
    (stdlib 3.13.2) maps.erl:188: :maps.get(:disposition, [{"content-type-params", [{"charset", "utf-8"}]}, {"disposition", "inline"}, {"disposition-params", []}], "inline")
    (gen_smtp 1.0.1) /tmp/build_d992ce7d/deps/gen_smtp/src/mimemail.erl:721: :mimemail.ensure_content_headers/7
    (gen_smtp 1.0.1) /tmp/build_d992ce7d/deps/gen_smtp/src/mimemail.erl:849: :mimemail.encode_component_part/1
    (gen_smtp 1.0.1) /tmp/build_d992ce7d/deps/gen_smtp/src/mimemail.erl:827: anonymous fn/2 in :mimemail.encode_component/5
    (stdlib 3.13.2) lists.erl:1254: :lists.flatmap/2
    (gen_smtp 1.0.1) /tmp/build_d992ce7d/deps/gen_smtp/src/mimemail.erl:824: :mimemail.encode_component/5
    (gen_smtp 1.0.1) /tmp/build_d992ce7d/deps/gen_smtp/src/mimemail.erl:163: :mimemail.encode/2
```

I know the breaking change on gen_smtp was switching from lists to maps, and I am not sure, but the issue might be on the `prepare_part` helper function.

Or of course, I am doing something wrong.

**Comment by princemaple** [comment]
Hi, do you see anything about Swoosh in the stacktrace?
Could you try removing `_build` and recompile?

**Comment by gabrielrinaldi** [comment]
@princemaple yes, the error is triggered from here:
`(swoosh 1.1.1) lib/swoosh/adapters/smtp.ex:46: Swoosh.Adapters.SMTP.deliver/2`

Removing `_build` does not change anything, unfortunately.

**Comment by princemaple** [comment]
The parameter is conditionally compiled with the gen_smtp version.
https://github.com/swoosh/swoosh/blob/master/lib/swoosh/adapters/smtp/helpers.ex#L21-L29

I'm going to test with my gmail account...

**Comment by gabrielrinaldi** [comment]
@princemaple the `@parameter` is working, I get version 1 and `%{}`, the issue seem to be when preparing the part: https://github.com/swoosh/swoosh/blob/master/lib/swoosh/adapters/smtp/helpers.ex#L134-L148

I think the part might be in the wrong format, but not sure. At least the error happens with those values.

**Comment by princemaple** [comment]
Yep that's what I was trying to figure out. I don't normally use SMTP, it's a little troublesome for me to test right now, but working on it.

**Comment by princemaple** [comment]
I managed to send an email via SMTP using latest Swoosh and latest gen_smtp.

**Comment by princemaple** [comment]
I will test something different now. Could be something about multipart.

**Comment by gabrielrinaldi** [comment]
Yes, that makes sense, I am sending a multipart email. Thanks a lot for looking into it.

**Comment by princemaple** [comment]
Indeed breaks multipart. Well. I hope I can fix it. I'm not smtp expert.

**Comment by princemaple** [comment]
Give 1.1.2 a go.

**Comment by gabrielrinaldi** [comment]
@princemaple perfect, thank you so much for fixing this so fast!
