### ISSUE TITLE
Swoosh.TestAssertions do not account for deliver_many.

### ISSUE THREAD

**Issue by zorn** [swoosh/swoosh#560]
Working in my own side project today I was trying to use `assert_email_sent` after a `deliver_many` call. I don't think this is working. Might be doing it wrong. Not sure. My current test is something like this:

```elixir
  describe "send_email_notification_batch/1" do
    setup [:with_various_delivery_status]

    test "success: emails we sent", %{group: group} do
      notes = Notifications.list_email_notifications_ready_for_delivery(prefix: group.subdomain)

      {:ok, _} = Notifications.send_email_notification_batch(prefix: group.subdomain)

      for note <- notes do
        assert_email_sent(Guildflow.NewMessageEmailNotification.new(note))
      end
    end
  end
```

And the failure is a bad match:

<img width="1904" alt="Screen Shot 2021-01-09 at 6 04 11 PM" src="https://user-images.githubusercontent.com/52168/104110424-6efba880-52a5-11eb-9e5a-89eee4937ba6.png">

Poking around the code I'm not sure `Swoosh.TestAssertions` ever expect that kind of message.

**Comment by princemaple** [comment]
Right. Currently `Swoosh.TestAssertions` is not equipped with the necessary tools to deal with `deliver_many`. As a workaround you can just go `assert_receive` until something like `assert_emails_sent` is added. Note, `deliver_many` will not behave like multiple calls to `deliver`, it is meant to be different.

**Comment by geeksilva97** [comment]
Can I work on that? :eyes:

**Comment by princemaple** [comment]
Yeah. https://github.com/swoosh/swoosh/pull/721 take this into consideration, though.

**Comment by geeksilva97** [comment]
Okay.
