### ISSUE TITLE
Swoosh breaking for major version detection for gen_smtp 1.1.1

### ISSUE THREAD

**Issue by aselder** [swoosh/swoosh#578]
Today we updated to gen_smtp version 1.1.1 and started getting errors like:

`(BadMapError expected a map, got: [])`

stack trace:
```
BadMapError: expected a map, got: []
  File "maps.erl", line 188, in :maps.get/3
  File "/app/deps/gen_smtp/src/mimemail.erl", line 708, in :mimemail.ensure_content_headers/7
  File "/app/deps/gen_smtp/src/mimemail.erl", line 160, in :mimemail.encode/2
  File "lib/api_v1/email/adapters/amazon_ses.ex", line 14, in ApiV1.Email.Adapters.AmazonSes.deliver/2
```

It looks like a change in gen_stmp broke the major version detection in Swoosh. See https://github.com/gen-smtp/gen_smtp/compare/1.1.0...1.1.1

It looks like they renamed the application from `gen_smtp_application` to `application`, which swoosh was relying on.

See https://github.com/swoosh/swoosh/blob/0ea43246d7fea0ae78fb528121be7b6fd87efc5a/lib/swoosh/adapters/smtp/helpers.ex#L23

**Comment by princemaple** [comment]
Thanks for the helpful information.

**Comment by princemaple** [comment]
Fixed in 1.3.4

**Comment by CGenie** [comment]
I'm using swoosh 1.5.2 and getting the same error as in the description of the ticket with the simple code:
```elixir
email = new |> from("<some-email>") |> to("<some-other-email>") |> subject("Test") |> text_body("Hello world")
WODR.Importer.Mailer.deliver(email)
```

**Comment by princemaple** [comment]
@CGenie try deleting the `_build` folder and recompile everything.

**Comment by CGenie** [comment]
Ah ok seems to work, thank you!
