### ISSUE TITLE
Set custom headers in Gmail adapter

### ISSUE THREAD

**Issue by reichert621** [swoosh/swoosh#585]
Is it possible to set custom headers in the Gmail adapter?

I'm trying to set the `"References"` and `"In-Reply-To"` in order to send messages as replies to threads (https://developers.google.com/gmail/api/guides/sending). Am I approaching this wrong?

**Comment by princemaple** [comment]
If you could leave a link to the docs or even send a PR, it'd be greatly appreciate. Cheers.

**Comment by reichert621** [comment]
hey @princemaple! before I dig into it I just wanted to double check that I'm thinking about this correctly... I'm just trying to send a message as a reply to an existing thread. am I right in thinking I just need to figure out a way for these headers to be passed though?

**Comment by princemaple** [comment]
Hi @reichert621 I'm not familiar with Gmail API, or how to send a reply to a thread. Maybe @mpran (who contributed the gmail adapter) can chime in?

**Comment by princemaple** [comment]
If it's only a matter of setting headers, should be easy to find out 😄

**Comment by reichert621** [comment]
I hope it's that simple! I'll wait for @mpran to chime in, but otherwise I can look into it tomorrow :+1:

**Comment by reichert621** [comment]
@princemaple I gave it a shot in this PR, but so far no luck with the replies... does anything look off in the code to you? https://github.com/swoosh/swoosh/pull/587

**Comment by princemaple** [comment]
There is a chance that the suffix of your subject needs to match the original subject. Just guessing...

**Comment by princemaple** [comment]
Correctly setting the custom headers, but I can't get the reply to show up in a thread either.

**Comment by reichert621** [comment]
yeah, i discovered that the gmail `thread_id` also needs to be passed through in the request in order for this to work 🤷

**Comment by hindkaer** [comment]
Hey!

Im struggling with the exact same issue, but i can't seem to find out how i should pass the `thread_id` into the Swoosh Email object. Could you explain that for me? :)
