### ISSUE TITLE
Sending cause error on certificate (unknown_ca)

### ISSUE THREAD

**Issue by xward** [swoosh/swoosh#586]
when calling `deliver(swoosh_email)` :
```
{:error, {:tls_alert, {:unknown_ca, 'TLS client: In state certify at ssl_handshake.erl:1895 generated CLIENT ALERT: Fatal - Unknown CA\n'}}}
```
It appends right after a new deploy, was working fine before.

Is it a problem from hackney certificate became obsolete ? How should I fix this right ?

Thanks a lot !

**Comment by xward** [comment]
I "fixed" it with this patch:
```
      email
      [....]
      |> Swoosh.Email.new()
      |> Map.put(:private, %{hackney_options: @hackney_options})
```

And in my Dockerfile I added:
```
RUN update-ca-certificates
RUN ln -fs /etc/ssl/certs/ca-certificates.crt /etc/ssl/cert.pem
```

The elixir Swoosh config part I did was quite dirty, how to make it sweet ? :)

**Comment by princemaple** [comment]
Hi, this happened to me once. I simply redeployed and it seemed to be "fixed". I'm not exactly sure what happened.

I guess maybe I should switch from hackney to Finch.

**Comment by princemaple** [comment]
So short answer is you may not need to do what you did.

Longer answer is I don't know what really happened. Long term speaking it might be safer to base the http client on a `mint` based library, which `finch` is one, that would use CA information from the `castore` package. I might make a switch at some point.

**Comment by princemaple** [comment]
Are you on Mailjet? Someone on Slack pinged me saying they have this issue.

**Comment by princemaple** [comment]
![Screenshot_20210508-074840](https://user-images.githubusercontent.com/1329716/117512005-1b3e6900-afd2-11eb-915b-5048c6fa7b75.png)
