### ISSUE TITLE
Why OTP 22+

### ISSUE THREAD

**Issue by derek-zhou** [swoosh/swoosh#592]
The Swoosh document states that it required OTP22+. However, all the Erlang deps such as `:gen_smtp` and `:hackney` works in OTP 21. And my limited testing (with SMTP) seems to indicate it works with OTP 21. So what is supposed _not_ to work in OTP 21?

**Comment by princemaple** [comment]
¯\_(ツ)_/¯ it's a documentation error. so 21 is actually supported as of now. (it's in the CI matrix)
however, it's probably not worth changing it now given how close OTP 24 is around the corner.
We normally support 3 OTP versions as 4 Elixir versions.

**Comment by derek-zhou** [comment]
got it, thanks
