### ISSUE TITLE
501 Syntax error - line too long when using SMTP adapter

### ISSUE THREAD

**Issue by ckruse** [swoosh/swoosh#593]
Hi there,

I am sending mails with the swoosh SMTP adapter for ages. Today I noticed that I could not send a HTML mail with a data URI image. The line is very long, and I get this error from the SMTP server: `501 Syntax error - line too long`. I guess this is because lines may only be 998 characters long.

This looks like a bug to me? I don't think that a library user should care about the transport restrictions, should they?

Best regards,
 CK

**Comment by princemaple** [comment]
Could you use an inline attachment?

**Comment by ckruse** [comment]
Maybe, I am working on that as a workaround

**Comment by princemaple** [comment]
BTW, I don't consider it a bug in Swoosh, because in order to mitigate this problem, Swoosh would have to understand HTML. Swoosh obviously has nothing to do with HTML parsing.

**Comment by ckruse** [comment]
Well, one could argue that quoted-printable or 7bit are simply not the right transfer encodings when a mail has lines longer than 998 characters. Maybe swoosh should choose base64 in this case?

**Comment by ckruse** [comment]
By the way, using an inline image works as a workaround

**Comment by princemaple** [comment]
> By the way, using an inline image works as a workaround

Thanks. Glad to know.

> Well, one could argue that quoted-printable or 7bit are simply not the right transfer encodings when a mail has lines longer than 998 characters. Maybe swoosh should choose base64 in this case?

Could you open a separate feature request for this one, so maybe someone will look into it and submit a PR?

**Comment by ckruse** [comment]
Done

**Comment by princemaple** [comment]
Thank you!
