### ISSUE TITLE
Swoosh for text messages

### ISSUE THREAD

**Issue by michalmuskala** [swoosh/swoosh#60]
I really like how swoosh is structured and I'd like to hear your opinion on possibility of extending the use of the library.

I'd like to propose we reuse the main ideas behind swoosh (adapters, local mailbox) and apply them to text messages - many things could be reused. However there are several approaches we could make:
- add text message handling directly to swoosh
- make a separate project that would use the same ideas from swoosh 
- create a `swoosh-text` project initially copying the code that should be reused, and eventually extracting common components into something like `swoosh-core`.

I don't want to impose anything, but I think it's an interesting idea worth exploring.

**Comment by barisbalic** [comment]
I wondered the same about sms/mms/push notifications before.  I think it's a good idea, but it's definitely very separate to email.  I think something like `swoosh-sms` could get away without any duplication, but the `%Swoosh.Email{}` interface would be a bit odd, aside from that an adapter would do the job.

Definitely worth more thought, I'm fairly sure @stevedomin will have considered some of this already, let's see what he says.

**Comment by stevedomin** [comment]
@michalmuskala sorry it took so long for me to reply to this one but I wanted to take the time to have a good proposal

I thought about somehow supporting text messages and push notification in swoosh, as it's something I need in my project but I couldn't really decide where it should live.

The cleaner way seems to be `swoosh` as a core library and then `swoosh-email`, `swoosh-message`, `swoosh-push-notification` and so on and so forth. But at the same if we decide Swoosh is more than an email library I'd be prefer to have everything in the same repo.

If we were to go with that approach (everything in the same repo), what would it take (for text messages)?

* Add a `Swoosh.Message` struct
* Nest the current email-related modules under `Swoosh.Email.*`
* Add a bunch of modules for handling text messages under `Swoosh.Message.*`

What would be shared:
* `Swoosh.Adapter`?
* The development plug?

What else do you have in mind @michalmuskala?
