### ISSUE TITLE
Shouldn't we skip ApiClient init if the adapter is not using it?

### ISSUE THREAD

**Issue by philss** [swoosh/swoosh#609]
Hi there :wave: 
First of all, thank you for this awesome library! :smiley: 

I'm trying to use it in _dev_ and test environments where I don't need the `ApiClient`. But it seems that I ways need to declare `Hackney` (or `Finch`) as dependencies because the `ApiClient` needs it, and the `ApiClient` is being initialized at application boot.

So my question is if we can avoid the _init_ of `ApiClient` if our configured adapter don't need it. I'm not sure how this could be done, but I imagined that it could be the Adapter's responsibility to initialize its dependencies. What do you think?

**Comment by princemaple** [comment]
I guess we should add a Noop API Client that simply OK on init. Do you want to add one?

**Comment by philss** [comment]
@princemaple thanks for the quick response! I can do that. :+1: 
The idea is to use this Noop as the default API Client instead of Hackney?

**Comment by princemaple** [comment]
It'd be a breaking change, so not really. We'd document it that if absolutely no hackney exists and init is causing trouble, config to use Noop API Client.

**Comment by philss** [comment]
Got it. I managed to get this working by setting `config :swoosh, :api_client, false`. Maybe just document this instead of adding a new Noop module is enough. WDYT?
