### ISSUE TITLE
Add json endpoint for mailbox preview

### ISSUE THREAD

**Issue by michalmuskala** [swoosh/swoosh#61]
When doing end-to-end testing with frontend of features like account registration that involve unique tokens and things like that, it would be useful to have a json version of the mailbox that the tests could query.

I did recently something similar in one of our projects. If you find this idea worth considering I could work on it.

**Comment by stevedomin** [comment]
That sounds like a fantastic idea!

On a somewhat related note, I'm also planning on making `Swoosh.TestAdapter` work better with integration testing.

**Comment by tlvenn** [comment]
Any update on this ?

**Comment by stevedomin** [comment]
@tlvenn definitely not a priority for now but would gladly accept any PR for it :)

**Comment by sagarppatil** [comment]
👋 hello! I was thinking of picking this up (if this is still needed), but needed to understand what might work best!

1. Separate JSON endpoints
2. Same endpoints with headers specifying JSON/HTML response.

I prefer the second approach but wanted to understand if that would work for others as well...

cc @stevedomin @michalmuskala

**Comment by princemaple** [comment]
Can still be good for integration test. Since it'd be a new feature, I'm OK with either way.
