### ISSUE TITLE
Telemetry events

### ISSUE THREAD

**Issue by joshnuss** [swoosh/swoosh#613]
Hi,

Thanks for created this useful library.

Would you be interested in adding `telemetry` events?
I think it would be useful for folks that want to have a dashboard for to track their emails.

# Example

Attach a telemetry handler for sent email:

```elixir
# in Application.start
:telemetry.attach("my-email-handler", [:swoosh, :mail, :sent], &MyHandler.handler_event/4, nil)
```

Then in the handler, push the event to StatsD, DataDog, Appsignal etc..

```elixir
defmodule MyHandler do
  def handle_event([:swoosh, :mail, :sent], measurement, meta, _) do
     # send to statsd or wtvr dashboard 
  end
end
```

If it's something you're interested in, LMK, and I'll open a PR.

**Comment by princemaple** [comment]
Hi @joshnuss ,

Yes. Some telemetry can be interesting. Especially for the people who use a provider that doesn't have it already.

Thanks!
