### ISSUE TITLE
mailgun adapter constructing bad URL

### ISSUE THREAD

**Issue by dtrce** [swoosh/swoosh#63]
maingun's @base_url var is missing / at the end hence constructing a url like this: https://api.mailgun.net/v3domain.com/messages. 

I was able to work around this by adding / in front of my domain_name config.

**Comment by stevedomin** [comment]
Thanks for reporting this. The docs are wrong, it's expected that domain would have a `/`.

But this is a really crappy experience so I'm going to change that :)

**Comment by barisbalic** [comment]
This is mentioned in one of the other issues I created recently

**Comment by stevedomin** [comment]
@dtrce fixed in master (75d9a3bfa64ff2db43f13755ab447669e371c4db)

@barisbalic which one?

**Comment by barisbalic** [comment]
Sorry, sent the email without finishing the reply, it was mentioned in #56 but now that you fixed it, it's 👍

**Comment by brentonannan** [comment]
Could we get a release on hex with this fix in it, please?

**Comment by stevedomin** [comment]
Waiting on https://github.com/swoosh/swoosh/pull/71 and I'll push a release out.

**Comment by brentonannan** [comment]
Tops, thanks.

**Comment by stevedomin** [comment]
@brentonannan v0.3.0 is out!

**Comment by brentonannan** [comment]
Awesome, thanks @stevedomin.
