### ISSUE TITLE
Better deliver_many documentation

### ISSUE THREAD

**Issue by odarriba** [swoosh/swoosh#636]
**Version: 1.5.1**

## Description

I'm getting an error when trying to call `deliver_many` with Sendgrid adapter in Swoosh. I'm one version behind latest release, but it looks like it happens also on main branch.

What do you think about having a fallback if no `deliver_many` implementation is there or  a note about this on the documentation of the `Swoosh.Mailer.deliver_many`? I know it is documented (I found it later) on `Swoosh.Adapter` module, but that module seems more for adapter's developers rather than final users.

I think that a bit of extra documentation in `Swoosh.Mailer` could be helpful for most users - specially about this `deliver_many` partial availability. What do you think?

If there is aim to accept PR's, I would be happy to contribute with some changes for this 🤗

**Comment by princemaple** [comment]
PRs are always welcome!

**Comment by geeksilva97** [comment]
I can give it a try.
