### ISSUE TITLE
Can't put API key in environment variable

### ISSUE THREAD

**Issue by erez-rabih** [swoosh/swoosh#64]
Hi
I'm trying to put the Sendgrid API key in an environment variable rather than hardcoded inside config.exs.

This is what my config looks like:
```elixir
config :my_app, MyApp.Mailer,
  adapter: Swoosh.Adapters.Sendgrid,
  api_key: System.get_env("SENDGRID_API_KEY")
```

It looks like the credentials are loaded fine on development with `mix run --no-halt` but when I run on production mode `MIX_ENV=prod` the environment variable is not being loaded correctly although I see them on `Application.get_all_env(:my_app)`
When I replace the get_env with the explicit API key everything works well.

What am I missing here?

**Comment by stevedomin** [comment]
The preferred way of using environment variable for config is to use the a `{:system, "ENV_VAR"}` tuple, otherwise the environment variable will be loaded at compile time rather than runtime.

Your example would look like this:

```elixir
config :my_app, MyApp.Mailer,
  adapter: Swoosh.Adapters.Sendgrid,
  api_key: {:system, "SENDGRID_API_KEY"}
```

This is documented in [Swoosh.Mailer](https://hexdocs.pm/swoosh/Swoosh.Mailer.html) but should probably be shown elsewhere.

**Comment by erez-rabih** [comment]
@stevedomin Thanks for the fast response.

I saw the documentation in Swoosh.Mailer and fixed the issue.

I'm kind of new to Elixir - is {:system, "ENV_VAR"} a standard way to load environment variables to config.exs in elixir or is it something specific to swoosh?

**Comment by stevedomin** [comment]
It's not standard but it's not specific to Swoosh either, other
Elixir projects like Phoenix have adopted it

**Comment by stevedomin** [comment]
@erez-rabih closing this one, feel free to get in touch if you run into other issues!
