### ISSUE TITLE
Can't configure AWS or SMTP Adapters to send emails.

### ISSUE THREAD

**Issue by SamuelMTDavies** [swoosh/swoosh#648]
I am new to Elixir and Pheonix and have set up a new application and added in Pheonix Auth. I am trying to send emails via AWS SES with via SMTP or the API. I have got the Local Adapter working but nothing I have done to try and send real emails has worked. 

I have tried using Finch and Hackney but to no avail. I am sending the email to and from the AWS SES verified email address as it's still in sandbox. I'm not getting any errors in the console

### _dev.exs file_
```
config :swoosh,
api_client: Swoosh.ApiClient.Finch,
adapter: Swoosh.Adapters.AmazonSES,
region: "eu-west-1",
access_key: "access_key",
secret: "secret_key"

I've also tried the following with all the SMTP ports the are mentioned on AWS SES

adapter: Swoosh.Adapters.SMTP,
relay: "email-smtp.eu-west-1.amazonaws.com",
username: "username",
password: "password",
tls: :always,
auth: :always,
port: 465
```

_**application.exs file**_

```
children = 
[...
{Finch, name: Swoosh.Finch}
]
```

_**mix.exs file**_
```
{:swoosh, "~> 1.5"},
{:gen_smtp, "~> 1.1"},
{:hackney, "~> 1.18"},
{:finch, "~> 0.8"}
```

I really don't know where I'm going wrong, I am happy to use the local adapter for my dev environment but I need to ensure the config for production also works.

**Comment by princemaple** [comment]
Hi, can we at least have some logs? Maybe the return value of `Mailer.deliver` as well.

**Comment by SamuelMTDavies** [comment]
I'd be happy to. but when I'm running this using mix phx.server there are just logs relating to the DB and Controllers.

Are there any more specific commands I can run to get you a more detailed log? or the return value you are after? I'm afraid as a complete newbie to Elixir and Pheonix I need a little hand-holding and pointing in the right direction as I don't know how to give you what you're asking for.

**Comment by princemaple** [comment]
Pipe your deliver call into `|> IO.inspect(label: "Mail")`

**Comment by SamuelMTDavies** [comment]
`Mail: {:ok,
 %Swoosh.Email{
   assigns: %{},
   attachments: [],
   bcc: [],
   cc: [],
   from: {"ME", "me@myemail.com"},
   headers: %{},
   html_body: nil,
   private: %{},
   provider_options: %{},
   reply_to: nil,
   subject: "Confirmation instructions",
   text_body: "\n==============================\n\nHi me@myemail.com,\n\nYou can confirm your account by visiting the URL below:\n\nhttp://localhost:4000/users/confirm/y1-RavBt-OobrhvxCMeHUkfUB9B38qqm_B6wm3qdd4o\n\nIf you didn't create an account with us, please ignore this.\n\n==============================\n",
   to: [{"", "me@myemail.com"}]
 }}`

**Comment by princemaple** [comment]
This doesn't look right. None of `SMTP`, `AmazonSES` or `Local` return this type. Can I see your code?

**Comment by SamuelMTDavies** [comment]
You can see the code on this repo

https://github.com/SamuelMTDavies/pheonix

the deliver email call is in lib/uown/accounts/user_notifier

Thanks for all the help and how quick you are its much appreciated.

**Comment by princemaple** [comment]
```elixir
Mailer.deliver!(email)
```

Change this chunk to the above and you will see the error.
https://github.com/SamuelMTDavies/pheonix/blob/main/lib/uown/accounts/user_notifier.ex#L16-L19

**Comment by princemaple** [comment]
You can also add `{:ok, _} = ` to the front of this line

**Comment by princemaple** [comment]
The 2 ways mentioned above are just for you to see the error.

How to properly handle the error, though, you will need to get more familiar with Elixir and Phoenix to figure out. It depends on how you want your app to behave, so I can't tell you what's the best way.

**Comment by SamuelMTDavies** [comment]
Ok thanks I will try that when I get back to my laptop.

I need to try and understand it all better because both lines you referenced are generated by mix phx.gen.auth so I had assumed that it would follow good general best practice for Pheonix.

**Comment by princemaple** [comment]
Generated code isn't supposed to be the final code. It's just a template.

**Comment by SamuelMTDavies** [comment]
I understand but I haven't seen any mention or signposting as to what parts they expect you to customise at least in relation to the emails. Once I've done your suggested changes I will see what error(s) I hit.

**Comment by SamuelMTDavies** [comment]
> {:ok, _} =

I get the following:
![Screenshot 2021-12-13 at 12 50 49](https://user-images.githubusercontent.com/10135240/145815737-c4aa8211-cdc1-4ce9-bf36-c73f4a942784.png)




`Mailer.deliver!(email)`


`Change this chunk to the above and you will see the error. https://github.com/SamuelMTDavies/pheonix/blob/main/lib/uown/accounts/user_notifier.ex#L16-L19`


Same issue if I make this change. I have been trying to follow the code and I don't think it's even reaching Swoosh. I don't understand why there is a pattern match error for an underscore? Or is it not able to match the entire tuple?

**Comment by SamuelMTDavies** [comment]
So i've been playing around a lot and i think I found that my config was being overwritten and the syntax was slightly wrong.

![Screenshot 2021-12-13 at 14 06 49](https://user-images.githubusercontent.com/10135240/145827539-368149f7-b058-4a2a-970d-986b4ffeb519.png)


I am now getting this error - is swoosh not set up to deliver messages in the dev environment? Just wondering why the false prefix is there on the deliver funtion.

**Comment by princemaple** [comment]
You haven't run `mix deps.get` after you added `hackney/finch` to your deps.

**Comment by SamuelMTDavies** [comment]
> You haven't run `mix deps.get` after you added `hackney/finch` to your deps.

I had definitely run it and I've deleted the _build folder and run mix phx.server from scratch.

I keep alternating between these two errors as I play with the config. Im at the point of removing everything related to swoosh, gen_smtp, Hackney and finch and trying again from scratch.

**Comment by princemaple** [comment]
OK you probably just haven't committed your code since. Your repo suggests that `mix deps.get` hasn't been run, but it's 2 days old.

In your config there is `config :swoosh, :api_client, false`. Remove [this line](https://github.com/SamuelMTDavies/pheonix/blob/main/config/config.exs#L30). This should resolve the issue.

**Comment by princemaple** [comment]
Oh actually more issues with your config.

in `prod.exs`

```elixir
config :swoosh,
  adapter: Swoosh.Adapters.AmazonSES,
  region: "eu-west-1",
  access_key: "key",
  secret: "secret"
```

Is totally wrong.

Remove `:api_client, Swoosh.ApiClient.Finch`

Leave

```elixir
config :swoosh,
  adapter: Swoosh.Adapters.AmazonSES,
  region: "eu-west-1",
  access_key: "key",
  secret: "secret"
```

**Comment by princemaple** [comment]
The one in your `dev.exs` is correct.

```
config :swoosh,
api_client: Swoosh.ApiClient.Finch,
adapter: Swoosh.Adapters.AmazonSES,
region: "eu-west-1",
access_key: "key",
secret: "secret"
```

**Comment by SamuelMTDavies** [comment]
Yeah this is what I have been suspecting. That I have conflicting config that is maybe intefering with one another.

I will re commit where I get to. Hopefully I strike upon the right settings and don't have anything surplus to what I am after.

**Comment by princemaple** [comment]
Yup, good luck.
