### ISSUE TITLE
Add OhMySMTP adapter

### ISSUE THREAD

**Issue by taobojlen** [swoosh/swoosh#656]
It'd be great if Swoosh included an adapter for [OhMySMTP](https://ohmysmtp.com/), a green and privacy-focused transactional email provider.

I've written a basic adapter for this in my own app. Would there be interest in adding this to Swoosh? If so, I'm happy to open a PR.

**Comment by princemaple** [comment]
Yeah looks like a good service provider, feel free to send a PR.

**Comment by taobojlen** [comment]
Okay, thanks! I'll work on this over the next few weeks then.
