### ISSUE TITLE
Option to set default sender for all the mails.

### ISSUE THREAD

**Issue by pankaj-ag** [swoosh/swoosh#657]
### Describe the bug

It's not a bug though. I just want to check if there is a way to set the default sender in the config or mailer? 
I looked at the docs but could not find that yet. 

### Steps to Reproduce the Bug or Issue

Not Applicable 

### Expected behavior

Not Applicable 

### Screenshots or Videos

Not Applicable 

### Platform

- OTP:
- Elixir:

### Additional context

Not Applicable

**Comment by princemaple** [comment]
Hi, you can add a function to your Mailer module or any module of your choice.

```elixir
import Swoosh.Email

def default_email do
  from(new(), {"Your name", "Your email"})
end
```

And use this function instead of `new()` from `Swoosh.Email` to start building your email.

**Comment by pankaj-ag** [comment]
Got it thanks.
