### ISSUE TITLE
Allow using custom CIDs for inline attachments

### ISSUE THREAD

**Issue by taobojlen** [swoosh/swoosh#658]
**Is your feature request related to a problem? Please describe.**

The docs state that:
> Inline attachments by default use their filename (or basename of the path if filename is not specified) as cid, in relevant adapters.

There appears to be no way to override this. However, you might want to attach multiple files with the same name, or you might not be in control of the email's HTML where CIDs are already defined.

**Describe the solution you'd like**
You could do something like `Swoosh.Attachment.new({:data, attachment_data}, inline: true, cid: "custom-cid")` when building attachments.

**Describe alternatives you've considered**
You can work around the problem in a few ways (like just not attaching multiple files with the same name), but this would be a cleaner solution -- at least for my use case.

**Additional context**
My specific use case is an email forwarding service where CIDs are already set in the email HTML.

**Comment by princemaple** [comment]
Hi, which adapter do you use? `cid` is currently only relevant in PostMark.

**Comment by princemaple** [comment]
ping

**Comment by princemaple** [comment]
Okay. I'm happy to merge it in, if you add the cid on attachment in the same PR, or via a separate PR.

**Comment by taobojlen** [comment]
Thanks! I've opened #663 for now; after that's approved and merged I'll add this custom CID feature.

**Comment by princemaple** [comment]
Thanks for your great PRs. I've released 1.6.0
