### ISSUE TITLE
Attachments show as "noname"

### ISSUE THREAD

**Issue by blackham** [swoosh/swoosh#669]
### Describe the bug

When I use Swoosh to send an inline image as an .html email to gmail the filename ends up noname.  I am able to view the inline image correctly in the email, but when the users try to download the image it shows up as "noname".  Now, you could say this isn't a bug, which is what MS Outlook does, but we are better than that, no? 

I could only find similar issues with MS Outlook because MS is not following the RFC correctly. I'm not sure if that is what is going on here. 

### Steps to Reproduce the Bug or Issue

```
config :my_app, MyApp.Mailer,
  adapter: Swoosh.Adapters.SMTP,
  relay: "xxxxxxx",
  ssl: true,
  port: 465,
  retries: 2,
  no_mx_lookups: false
```

```
  html = function_to_make_html
  link_chart = function_to_make_png

    mail_obj = new()
      |> to("xxxxxxx")
      |> from("xxxxxx")
      |> subject("inline attachments are noname, but why?")
      |> html_body(html)
      |> text_body("Please use an HTML enabled email client to view this.")
      |> attachment(
        Swoosh.Attachment.new(
          {:data, link_chart},
          filename: "link_chart.png",
          content_type: "image/png",
          type: :inline)
      )
 
  mail_obj |> MyApp.Mailer.deliver
```

### Expected behavior

When I click to download the image I would expect it to have the default file name "link_chart.png". But I get "noname"

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/9464565/152419868-039037b6-9488-4a21-894b-9296e2f2e6ad.png)

### Platform

- OTP:
- Elixir:

**Comment by princemaple** [comment]
Hi, could you post your generated html?

**Comment by princemaple** [comment]
Closing with v1.6.2

**Comment by blackham** [comment]
That is a LOT of HTML.  But below is where the image is added. This image shows up perfect in the email. It's when they click on the download arrow in gmail that it displays "noname". I tried also setting name="xyz.png" and alt="test.png" in the html <img src>. (Just guessing, but same "noname" results)

```
        <tr>
          <td class="headerContent">
      
            <!-- // Begin Module: Standard Header Image \\ -->
            <img src="cid:link_chart.png" style="max-width:600px;" id="headerImage campaign-icon" mc:label="header_image" mc:edit="header_image" mc:allowdesigner mc:allowtext />
            <!-- // End Module: Standard Header Image \\ -->
      
          </td>
        </tr>
```

![image](https://user-images.githubusercontent.com/9464565/152446769-76297d4f-e15b-4f8c-8f94-283ed3724ed8.png)

**Comment by blackham** [comment]
Awesome! Works great now!
![image](https://user-images.githubusercontent.com/9464565/152447368-8ec9714c-6bf1-4403-87fd-c29df0973062.png)


Swoosh is #1 okay!

**Comment by princemaple** [comment]
Thanks for the confirmation!
