### ISSUE TITLE
Update OhMySmtp to MailPace (rename)

### ISSUE THREAD

**Issue by kurtome** [swoosh/swoosh#670]
**Is your feature request related to a problem? Please describe.**
OhMySTMP has been renamed to MailPace. The existing API URLs and headers could continue to work, however to reduce confusion a new adapter with the new name would be ideal. https://docs.mailpace.com/guide/moving_from_ohmysmtp

**Is your feature request related to a specific adapter? Please specify.**
`Swoosh.Adapters.OhMySmtp`

**Describe the solution you'd like**

- Copy the entire module `Swoosh.Adapters.OhMySmtp` with a new name `Swoosh.Adapters.MailPace`
- Mark the existing module deprecated
- Make sure to use the new API endpoints and headers in the new module as described in their [migration docs](https://docs.mailpace.com/guide/moving_from_ohmysmtp).

**Comment by princemaple** [comment]
That's a bit unfortunate. Well. We will deal with it. Thanks for letting us know.

**Comment by princemaple** [comment]
Hi @kurtome could you give #672 a whirl?

**Comment by taobojlen** [comment]
Thanks @princemaple -- yes, that's unfortunate timing! I'll be able to give the branch a go this weekend, if you can wait till then.

**Comment by taobojlen** [comment]
@princemaple it works in my app. Migration was easy, just needed a global find-and-replace `s/OhMySmtp/MailPace`.

**Comment by princemaple** [comment]
Thank you @taobojlen :)

**Comment by princemaple** [comment]
v1.6.3
