### ISSUE TITLE
Mailinator: Attachment removed

### ISSUE THREAD

**Issue by phanmn** [swoosh/swoosh#677]
### Describe the bug

Hi,

I'm using AmazonSES adapter to send an only text file email.

I can read email with Gmail, but in Mailinator, it shows `Attachment removed`.

Please give me a suggestion.

Many thanks!

### Steps to Reproduce the Bug or Issue

Send only text mail to Mailinator

![image](https://user-images.githubusercontent.com/3765536/156714687-c807d294-a560-4b67-bc13-570f9a9d386b.png)

![image](https://user-images.githubusercontent.com/3765536/156714733-0d67b22f-3768-4e16-956e-027c3fd29c0a.png)

### Platform

- OTP: 24
- Elixir: 1.13.2

**Comment by princemaple** [comment]
Hi @phanmn, if it worked when sending to gmail, I'd say that Swoosh is doing its job correctly.

Looking at the documentation of Mailinator, I saw this line:

> In addition, all emails in the public Mailinator system auto-delete after a few hours. They are un-retrievable after this happens. Public Mailinator emails also may not contain attachments (if an attachment is sent, it will either not be delivered, or have the attachments stripped before delivery).

That's most likely why you see this - they don't take attachments.

Swoosh doesn't alter your email in anyway.

**Comment by phanmn** [comment]
Hi @princemaple,

Thanks for your reply, I just send text only, no attachment.

I think Mailinator is checking `content-disposition` header, which Swoosh is setting `inline` for text/plain.

I tried to remove the code which sets `inline` at `https://github1s.com/swoosh/swoosh/blob/HEAD/lib/swoosh/adapters/smtp/helpers.ex#L143-L144` but no email can be sent after that.

Do you have any idea !?

**Comment by princemaple** [comment]
Could you post your code that sends the email? Thanks!

**Comment by phanmn** [comment]
Here is screenshot of my code

![image](https://user-images.githubusercontent.com/3765536/156736770-142d310f-268f-4dc0-bde6-f893c9228e32.png)

**Comment by phanmn** [comment]
Here is the detail of Swoosh email read by Gmail

![image](https://user-images.githubusercontent.com/3765536/156737456-b2eceeb9-9420-4c4c-9753-c22c5ec0bd67.png)

**Comment by princemaple** [comment]
Thanks. One thing I found weird was that in the mailinator screenshot, it shows 2 `text/plain` instead of 1 `text/plain` and 1 `text/html`.

**Comment by princemaple** [comment]
Hi,

I tested removing the "inline" part from Swoosh code base. Looks like `:gen_smtp` adds it anyway.

Swoosh:

```elixir
{"multipart", "alternative",
 [
   {"From", "a@outlook.com"},
   {"To", "b@hotmail.com"},
   {"Subject", "test"},
   {"Mime-Version", "1.0"}
 ],
 [
   {"text", "plain",
    [
      {"Content-Type", "text/plain; charset=\"utf-8\""},
      {"Content-Transfer-Encoding", "quoted-printable"}
    ], %{content_type_params: [{"charset", "utf-8"}], disposition_params: []},
    "test"},
   {"text", "html",
    [
      {"Content-Type", "text/html; charset=\"utf-8\""},
      {"Content-Transfer-Encoding", "quoted-printable"}
    ], %{content_type_params: [{"charset", "utf-8"}], disposition_params: []},
    "123123"}
 ]}
```

After `:gen_smtp` transformation:

```
From: a@outlook.com
To: b@hotmail.com
Subject: test
Mime-Version: 1.0
Content-Type: multipart/alternative;
        boundary="_=1z38303y03621106103h1e2m4f4g6h02=_"
Date: Fri, 4 Mar 2022 19:52:04 +1000
Message-ID: <1503237705d212498a66dd74099f648d@DESKTOP-9EPU6AP>


--_=1z38303y03621106103h1e2m4f4g6h02=_
Content-Type: text/plain;
         charset="utf-8"
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline

test
--_=1z38303y03621106103h1e2m4f4g6h02=_
Content-Type: text/html;
         charset="utf-8"
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline

123123
--_=1z38303y03621106103h1e2m4f4g6h02=_--
```

I'm not familiar enough with the spec to know whether it's supposed to be there or not. It's either a parse error in mailinator or a bug in `:gen_smtp`

**Comment by phanmn** [comment]
Thank @princemaple
