### ISSUE TITLE
Warning when compiling swoosh (ExAws.Config.new/1 is undefined)

### ISSUE THREAD

**Issue by altdsoy** [swoosh/swoosh#685]
### Describe the bug

Since 1.6.5 there's the following warning when compiling:
```
warning: ExAws.Config.new/1 is undefined (module ExAws.Config is not available or is yet to be defined)
  lib/swoosh/adapters/ex_aws_amazon_ses.ex:63: Swoosh.Adapters.ExAwsAmazonSES.deliver/2
```

### Steps to Reproduce the Bug or Issue

Add Swoosh in the project dependency and compile the project.

### Expected behavior

Even if we do not use the ExAws adapter we should not get this warning.

### Platform

- OTP: 24.2.2
- Elixir: 1.13.3

**Comment by princemaple** [comment]
Thanks for reporting. I forgot to suppress this warning.

**Comment by princemaple** [comment]
Releasing 1.6.6 right now

**Comment by altdsoy** [comment]
That was fast :)
Thanks!

**Comment by princemaple** [comment]
🙂🙏
