### ISSUE TITLE
weird html_body formatting when using assert_email_sent 

### ISSUE THREAD

**Issue by tidusIO** [swoosh/swoosh#693]
### Describe the bug

I've started to use MJML to generate the HTML for my mails. Following strange behaviour.

Now my assert_email_sent(email) commands are failing. The reason is, that the HTML of the "received" mail seems to get reformatted. The order of attributes in tables changed.

Following example of the two versions:

`<table cellpadding=\"0\" width=\"650\" border=\"0\" cellspacing=\"0\" role=\"presentation\" align=\"center\" style=\"width:650px;\">`

`<table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" border=\"0\" width=\"650\" style=\"width:650px;\">`

I tried to check the source code of the swoosh, but I didn't really find where this happens.

As workaround I tried using assert_email_sent(subject: ""). But this seems to check only the last mail. And we're having some tests sending multiple mails within one test.

### Steps to Reproduce the Bug or Issue

Using an html_body with the following HTML:

`<table cellpadding=\"0\" width=\"650\" border=\"0\" cellspacing=\"0\" role=\"presentation\" align=\"center\" style=\"width:650px;\">`

`<table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" border=\"0\" width=\"650\" style=\"width:650px;\">`

### Platform

- OTP: 24
- Elixir: 1.13.4

**Comment by princemaple** [comment]
Hi, we don't do anything with the html or text body. They are sent verbatim. If you can setup a simple reproduction, I can help take a look, but it's most likely not swoosh doing something weird here.

**Comment by princemaple** [comment]
I just played with `mjml` for a minute. It outputs html attributes in different orders between renders.

My guess is that the rust underlying data structure it used for attributes is a map. Maps are not ordered, so it's not reliable to test the whole generated HTML.

You will have to figure out a way to test it properly.

https://user-images.githubusercontent.com/1329716/169750149-dffd6cd9-6102-4a0a-893c-e95fbb349505.mp4

**Comment by tidusIO** [comment]
Okay, nice for the quick reply. I will check then how I can solve it.

just another quick question. Is it intention that assert_email_sent(subject: "") just checks the last mail and not the mails in the pid messages field?

**Comment by princemaple** [comment]
You can call it multiple times. Its implementation is a simple receive. So each time you call it, it tries to receive an email.

**Comment by princemaple** [comment]
You can also pass it a `fun/1`. It will get the email as the argument.

**Comment by tidusIO** [comment]
If other people will find this issue or run into this problem:
https://github.com/adoptoposs/mjml_nif/pull/63

It's really a problem in the MJML rust implementation. If using the orderedmap feature it will fix the problem :)
