### ISSUE TITLE
Add headers support in assert_email_sent

### ISSUE THREAD

**Issue by MatheusBuss** [swoosh/swoosh#701]
**Is your feature request related to a problem? Please describe.**
I'm implementing a functionality that requires using email headers, but the function `assert_equal` has no clause for headers, which makes testing the sent email more difficult.

**Describe the solution you'd like**
Add a clause that covers email headers on `assert_equal`

Not sure if there's something I'm missing that already covers this. If not it appears to be a straightforward feature I could make the PR.

**Comment by princemaple** [comment]
Adding a clause is good, happy to accept that. Otherwise you could just pass in a function https://github.com/swoosh/swoosh/blob/main/lib/swoosh/test_assertions.ex#L96-L99
