### ISSUE TITLE
send email in background, but in a simple way

### ISSUE THREAD

**Issue by ally9335** [swoosh/swoosh#713]
Is there a simple way to send email in backround, with a single command? For instance, `Bamboo` has `deliver_later` method

**Comment by princemaple** [comment]
https://github.com/swoosh/swoosh#async-emails

**Comment by ally9335** [comment]
@princemaple that's not it. I'm not asking how to send email in background in general via Swoosh. But in a simple way.

**Comment by princemaple** [comment]
It's an explicit decision to not do it in Swoosh as elixir and OTP already give you so much around background / Async jobs. It's irresponsible to provide a toy implementation that is not reliable at all in practice. If that suits you, you can simply write a function that wraps deliver in a `Task.start` and always call that function. Anything more serious needs to be handled by a lib that specifically targets this problem.

We think there shouldn't be a sync and an Async version of each lib. We believe every lib should be sync and be made Async either with OTP constructs or another lib.
