### ISSUE TITLE
Multiple reply_to addresses (Sendgrid)

### ISSUE THREAD

**Issue by ssbb** [swoosh/swoosh#738]
**Is your feature request related to a problem? Please describe.**
There should be a way to specify multiple addresses for `reply_to`.

**Is your feature request related to a specific adapter? Please specify.**
Sendgrid

Now there is a way to add multiple addresses in `reply_to` (at least in sendgrid) - https://docs.sendgrid.com/api-reference/mail-send/mail-send#multiple-reply-to-emails

I am thinking about preparing a PR but looks like it will affect `Email` type (which has `reply_to: mailbox() | nil`) so I am thinking how to do it and to not break everything else. Do you think it makes sense to change type to `[mailbox()] | []` and handle it everywhere?

**Comment by princemaple** [comment]
The only non-breaking way would be to keep `mailbox() | nil` and add `[mailbox()]` to it. There might be code in the wild that sets the email reply-to then set it back to `nil`. So we can't rely on the struct default value being updated.

Adapter code already handles `nil` case.

https://github.com/swoosh/swoosh/blob/4345854b73133f81865c42a7cb69055f8cc2831a/lib/swoosh/email.ex#L228-L231 Needs a clause to handle a list.

Adapter code for `Reply-To` list can be updated case by case if the need arises (provider support kicks in).

Mailgun allows you to specify `Reply-To` header via custom headers, so users can already specify multiple, given that they format the addresses by themselves.

You can add a clause for when `is_list(reply_to)` for Sendgrid. https://github.com/swoosh/swoosh/blob/4345854b73133f81865c42a7cb69055f8cc2831a/lib/swoosh/adapters/sendgrid.ex#L239-L242

Feel free to leave the rest to their users who wanted the support.

**Comment by ssbb** [comment]
Thank you!

I can't find any headers doc on sendgrid. I am sure I was used `reply-to` with them on another lib but `reply_to_list` is separated from this one. 

I'll prepare PR

**Comment by princemaple** [comment]
No worries. It was just an example for "case by case".

Thanks, looking forward to the PR.
