### ISSUE TITLE
Documentation for Swoosh.Adapters.SMTP inadeqete

### ISSUE THREAD

**Issue by Dinsmoor** [swoosh/swoosh#740]
See attached image, this configuration (inclusion of "ssl: true" will result in failure for STARTTLS servers, and no documentation anywhere for the SMTP adapter makes this clear.
![image](https://user-images.githubusercontent.com/3772345/209769058-a9a4598b-a31a-40ab-a7ce-5324495ad043.png)

Please make a note in the documentation that to use with STARTTLS you must omit the ssl configuration.

**Comment by princemaple** [comment]
Thank you!
