### ISSUE TITLE
Better API adapter documentation

### ISSUE THREAD

**Issue by Shadowbeetle** [swoosh/swoosh#742]
Version: 1.9.1

# Description

When using API adapters such as AmazonSES, Mailgun, or Sendgrid, it is not obvious from the documentation that it needs an API client. It is clearly stated in the [installation section](https://hexdocs.pm/swoosh/Swoosh.html#module-installation), however, it would be useful to link to it from the individual API Adapter pages. Especially considering that phx.gen.auth uses Swoosh by default, thus probably many don't even get to read it, as we can just straight up start configuring the adapter. I've seen [these](https://elixirforum.com/t/issues-sending-emails-with-swoosh/44707/3) two [discussions](https://elixirforum.com/t/swoosh-swoosh-adapters-smtp-vs-swoosh-adapters-amazonses/44850) on elixir forum that hints at this not being exclusively my problem.

Would it be ok if I opened a PR adding some explanation and a link to the installation section to each adapters `@moduledoc`?

**Comment by princemaple** [comment]
Thanks for the help! #743
