### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by LeeCrey** [swoosh/swoosh#754]
```
== Compilation error in file lib/swoosh/adapters/xml/helpers.ex ==
** (ArgumentError) lib file xmerl/include/xmerl.hrl could not be found
    (elixir 1.14.3) lib/record/extractor.ex:41: Record.Extractor.from_lib_file/1
    (elixir 1.14.3) lib/record/extractor.ex:18: Record.Extractor.from_or_from_lib_file/1
    (elixir 1.14.3) lib/record/extractor.ex:5: Record.Extractor.extract/2
    lib/swoosh/adapters/xml/helpers.ex:5: (module)
```
![Screenshot from 2023-03-19 19-25-11](https://user-images.githubusercontent.com/87988868/226189855-7fcc7fd3-c113-485d-9d5c-5e622b9988b0.png)

**Comment by princemaple** [comment]
How did you install your Erlang? What version is it?

**Comment by adamu** [comment]
Ot looks like some systems require xmerl to be installed separately: https://hexdocs.pm/sweet_xml/readme.html#installation

**Comment by princemaple** [comment]
Closing due to lack of response.

**Comment by LeeCrey** [comment]
Sorry for the late reply. Wasn't active for months. I am currently learning
Phoenix without swoosh. I will ask when i understand what the problem if
the probolem happen again. I installed the latest version of Erlang. I was
following some tutor. The Phoenix installation was success but the problem
was when i try to create new app.
