### ISSUE TITLE
Debugging help with {:error, {404, "404 page not found\n"}} coming from Swoosh

### ISSUE THREAD

**Issue by chrisdel101** [swoosh/swoosh#761]
I'm using mailgun and have confirmed the credentials work with curl, and I can confirm they are making into the `config.exs`.  I cafn also confirm that the email I am entering is verified by mailgun, and works from curl (here is just displayed as `tony.stark@example.com`). No logs are hitting mailgun, but this isn't reliable here since the curl'd emails are also aren't showing in logs

From the [getting started](https://hexdocs.pm/swoosh/Swoosh.html#module-getting-started) I call  
`iex> email = Sample.UserEmail.welcome(%{name: "Tony Stark", email: "tony.stark@example.com"})`

I get `{:error, {404, "404 page not found\n"}}`.  How can I debug this? How can I see what URL is being called? It's a black box and I can't find anyway to find the error.

```
config :sample, Sample.Mailer,
      adapter: Swoosh.Adapters.Mailgun,
      domain: System.get_env("MAILGUN_DOMAIN"),
      api_key: System.get_env("MAILGUN_API_KEY"),
      debug: true

 config :swoosh,
      api_client: Swoosh.ApiClient.Hackney

AND


  def welcome(user) do
    new()
    |> to({user.name, user.email})
    |> from({"Dr B Banner", "hulk.smash@example.com"})
    |> subject("Hello, Avengers!")
    |> html_body("<h1>Hello #{user.name}</h1>")
    |> text_body("Hello #{user.name}\n")
  end
```

More detailed [post](https://elixirforum.com/t/sending-email-mailgun-404-not-found-nothing-is-happening-no-debug-messages/55230)

**Comment by chrisdel101** [comment]
But it is configured. So the correct values are not getting through to it for some reason.

Is it definitely a response from mail gun then? No some default error?

This means the combination of domain and key is not getting packaged correctly, or the email address put in the command above is not making it to mailgun correctly. How can I check this?

**Comment by princemaple** [comment]
Swap your system get env with hard coded domain and try again

**Comment by chrisdel101** [comment]
So if I this the correct values log out. I also tried with hardcodeing values, but I still get 404. The correct values are not getting "through", but I don't really know what this means since I don't know how this works. 

```
config :sample, Sample.Mailer,
      adapter: Swoosh.Adapters.Mailgun,
      domain: System.get_env("MAILGUN_DOMAIN"),
      api_key: System.get_env("MAILGUN_API_KEY"),
      debug: true

IO.inspect(System.get_env("MAILGUN_DOMAIN"))
IO.inspect(System.get_env("MAILGUN_API_KEY"))
```

**Comment by princemaple** [comment]
Can you share your repo or post your mailer code

**Comment by chrisdel101** [comment]
Sure! BTW everything is just the default that comes with phoenix. 

Also the post I link to in the original has some code that is similar.

Mailer: https://github.com/chrisdel101/turnStile/blob/master/lib/turnStile/customer/staff/employee_notifier.ex
config: https://github.com/chrisdel101/turnStile/blob/master/config/config.exs
application (loading dot_env): https://github.com/chrisdel101/turnStile/blob/master/lib/turnStile/application.ex

I a calling this `iex> TurnStile.Staff.EmployeeNotifier.deliver("my_working_email@yahoo.com", "test subject", "test body")` which is in Mailer above.

**Comment by chrisdel101** [comment]
Do I have the domain wrong? If the entire sandbox URL is `https://api.mailgun.net/v3/sandbox1234567.mailgun.org` is the `domain'? This is what I have now. But I've tried every variation I can think of and I get 404 for no matter what.

The 404s are not even hitting mailgun connected to my account. They are not showing up in my logs

**Comment by chrisdel101** [comment]
Fixed. The issue was the domain was wrong as noted above. 

I spent an entire day on this. Wish there was a better day to debug! Would have caught this earlier if I could see the URL being constructed
