### ISSUE TITLE
Configuration of `:api_client` in an Umbrella app

### ISSUE THREAD

**Issue by thojanssens** [swoosh/swoosh#767]
### Describe the bug

When scaffolding an Umbrella app with Mix, the following `swoosh` configuration can be found in the global prod config file:

```elixir
config :swoosh, :api_client, MyApp.Finch
```

However I have multiple apps, and don’t really understand why this is then global, and which Finch instance should be specified.

When I scaffold the different Umbrella apps, I’ll typically have multiple Finch clients started by default:

```elixir
defmodule FooApp.Application do
  use Application

  def start(_type, _args) do
    children = [
      # ...
      {Finch, name: FooApp.Finch}
    ]
    Supervisor.start_link(children, strategy: :one_for_one, name: FooApp.Supervisor)
  end
end
```

```elixir
defmodule BarApp.Application do
  use Application

  def start(_type, _args) do
    children = [
      # ...
      {Finch, name: BarApp.Finch}
    ]
    Supervisor.start_link(children, strategy: :one_for_one, name: BarApp.Supervisor)
  end
end
```

As well as different Mailer apps:

```elixir
config :foo_app, FooApp.Mailer, adapter: Swoosh.Adapters.Local

config :bar_app, BarApp.Mailer, adapter: Swoosh.Adapters.Local
```

### Steps to Reproduce the Bug or Issue

```elixir
mix phx.new my_app --no-html --no-dashboard --no-live --no-assets --no-esbuild --no-gettext --no-tailwind --binary-id --umbrella
```

### Expected behavior

I expected to have a configuration per app?

### Additional context

I guess this is more of a question than a bug

**Comment by thojanssens** [comment]
Actually asked to clarify here https://elixirforum.com/t/configuration-of-swoosh-in-an-umbrella-app/55710/2

**Comment by princemaple** [comment]
Probably better asked in Phoenix as it's a phoenix generator?

**Comment by thojanssens** [comment]
Thank you @princemaple I asked for clarifications here: https://github.com/phoenixframework/phoenix/issues/5453

**Comment by princemaple** [comment]
Cheers. I don't use umbrella apps, so I wouldn't have a good idea where the best place to put the config is. Closing in favor of the issue on Phoenix and the post on forum.

However, I think the bottom line is, if the whole app is deployed to one place, i.e. the apps under this umbrella aren't deployed to different places in separation from other apps, it really doesn't matter. You can have one or many Finch instances. It only becomes tricky when you do separate deployments.

**Comment by thojanssens** [comment]
Do you think we can reopen this issue and mark it for enhancement?
https://elixirforum.com/t/59296/4
It would be nice to allow for multiple HTTP client when dealing with multiple apps independently deployed.

**Comment by princemaple** [comment]
Would this work...?

In both `FooApp` and `BarApp`, you start `MyApp.Finch`

You only use one config - `MyApp.Finch`

When you deploy, since they are in separate environments anyway, they won't interfere with each other...?

**Comment by thojanssens** [comment]
This won't work if in development I want to run `mix run --no-halt` from the root of the Umbrella.

Swoosh forces me to create a new app to share the HTTP client because of the global config. See this:
https://hexdocs.pm/elixir/1.15.7/library-guidelines.html#avoid-application-configuration

Instead of 
```elixir
post(url, headers, body, email)
```
we can have:
```elixir
post(url, headers, body, email, http_client)
```
where the `http_client` is optional and will take precedence from any global config.

The time zone database config is a good example:
```elixir
config :elixir, :time_zone_database, MyTimeZoneDatabase
```
or 
```elixir
Calendar.put_time_zone_database(MyTimeZoneDatabase)
```
or pass the database to the functions:
```elixir
DateTime.now("America/Sao_Paulo", MyTimeZoneDatabase)
```

**Comment by thojanssens** [comment]
I personally no longer need this feature (see Finch issue mentioned for my implemented solution). The point still remains that it is preferred not to rely on global config solely, but I no longer require this:)
Thank you for your attention in any case!

**Comment by princemaple** [comment]
Thanks for the update. The point about the application stands. I'll update it when I get some time.
