### ISSUE TITLE
Mailgun reply_to not working

### ISSUE THREAD

**Issue by justinbkay** [swoosh/swoosh#77]
I've configured email for use with mailgun.  The email is sending correctly through the mailgun api, but the reply_to isn't being added.  I switched to this library specifically for this feature, so it is important for me that this work.  I'll be happy to help troubleshoot/fix this issue.

```
defmodule NwreccOrg.SendMinisiteEmail do
  import Swoosh.Email
  def proxy(property, params) do
    unless Map.has_key?(params, :email) do
      params = Map.put(params, :email, "replyto@example.com")
    end

    new
    |> to({ property.name, property.email})
    |> reply_to(params.email)
    |> from("webmaster@example.com")
    |> subject("Email Contact")
    |> text_body(contact_us_text(params))
  end

  defp contact_us_text(params) do
    ....
  end
end
```

**Comment by stevedomin** [comment]
@justinbkay Hi! Thanks for the report, I'm looking into it now

**Comment by justinbkay** [comment]
If I use the mailbox preview, the reply_to is shown, but whatever is being
sent off to mailgun must not be quite right.

On Fri, May 13, 2016 at 2:22 PM, Steve Domin <notifications@github.com>
wrote:

> @justinbkay <https://github.com/justinbkay> Hi! Thanks for the report,
> I'm looking into it now
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/swoosh/swoosh/issues/77#issuecomment-219149610>
>



-- 
Sites:
http://jbkayconstruction.com
https://twitter.com/justinbkay
http://justinbkay.tumblr.com

It always takes longer than you expect, even when you take into account
Hofstadter’s Law.
- Hofstadter’s Law

**Comment by stevedomin** [comment]
@justinbkay can you tell me which version of Swoosh you are using? I can't reproduce this issue with master.

Also do you have the raw email with headers that you received by any chance? Should be quite easy to get depending on which email client you are using.

I really want to find out what's happening!

**Comment by justinbkay** [comment]
I'm using the most current.  I think it is working, the reply-to just
doesn't show up in the mailgun logs at all.  Sorry to have bothered you
with this.

On Fri, May 13, 2016 at 3:19 PM, Steve Domin <notifications@github.com>
wrote:

> @justinbkay <https://github.com/justinbkay> can you tell me which version
> of Swoosh you are using? I can't reproduce this issue with master.
>
> Also do you have the raw email with headers that you received by any
> chance? Should be quite easy to get depending on which email client you are
> using.
>
> I really want to find out what's happening!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/swoosh/swoosh/issues/77#issuecomment-219161847>
>



-- 
Sites:
http://jbkayconstruction.com
https://twitter.com/justinbkay
http://justinbkay.tumblr.com

It always takes longer than you expect, even when you take into account
Hofstadter’s Law.
- Hofstadter’s Law

**Comment by stevedomin** [comment]
Oh I see. Yes, it's not showing indeed, it's a shame.

No worries at all, if you run into any other issue, please let us know.
