### ISSUE TITLE
Allow passing an anonymize function to refute_email_sent

### ISSUE THREAD

**Issue by bitboxer** [swoosh/swoosh#770]
**Is your feature request related to a problem? Please describe.**

Similar to [here](https://github.com/swoosh/swoosh/pull/576) I want to use an anonymize function in the `refute_email_sent` to make sure I don't send a certain mail.

**Is your feature request related to a specific adapter? Please specify.**

No.

**Describe the solution you'd like**

A function that returns a boolean as a parameter.

**Comment by princemaple** [comment]
Do you want to give the new (experimental) TestAssertions module in v1.11 a go?

**Comment by bitboxer** [comment]
Yes, I love to try out new things. Where can I find it?

**Comment by princemaple** [comment]
https://hexdocs.pm/swoosh/Swoosh.X.TestAssertions.html

Introduced in https://github.com/swoosh/swoosh/pull/747

Simply upgrade to v1.11.0 to use this module.

https://github.com/swoosh/swoosh/blob/main/lib/swoosh/x_test_assertions.ex#L254 It can take a funciton.

**Comment by bitboxer** [comment]
Totally forgot to answer here, sorry. This works perfectly. Thanks for this <3.

**Comment by princemaple** [comment]
Cheers! This will probably become default in the next major version, but not sure when.

All you will have to do is remove `X.`. Hopefully that's easy enough.
