### ISSUE TITLE
Support for multiple API keys

### ISSUE THREAD

**Issue by Pavinati** [swoosh/swoosh#774]
**Is your feature request related to a problem? Please describe.**
My phoenix backend is multi tenant and I need to use different `api_key`s depending on which tenant is generating the email notification.
Is there a way to dinamically define the `api_key` to use instead of defining it once and for all in the config/runtime.exs?

**Is your feature request related to a specific adapter? Please specify.**
I'm using Sendgrid adapter, but the issue is broader

**Describe the solution you'd like**
I'd like to be able to pass the `api_key` as optional parameter when delivering mails. Othewise, configure a custom function to be called to retrieve the `api_key`. Or any other solution that better suits the Swoosh API.

**Describe alternatives you've considered**
I'm not really sure there is an alternative at the moment. I'd love to keep using Swoosh but if it can't be helped i might have to try out a different library or calling the adapter's REST API myself.

**Comment by princemaple** [comment]
Hi, you can pass api_key as kw list or map to deliver as a second argument.

**Comment by princemaple** [comment]
Config is different for every adapter. The feature is kinda documented here https://hexdocs.pm/swoosh/Swoosh.Mailer.html#module-examples probably not obvious enough...
