### ISSUE TITLE
Q: how can I test for provider error?

### ISSUE THREAD

**Issue by elvanja** [swoosh/swoosh#775]
Hi,

So I am trying to write a test in which I want to make sure I am logging appropriate information when email delivery fails at email provider side. E.g. provider may return `{:error, {401, "Forbidden"}}` if config is invalid. The only solution I could find so far was something like:

```elixir
use Mimic.DSL

test "with error" do
    stub MyApp.Mailer.deliver(_ignore) do
      {:error, {401, "Forbidden"}}
    end
end
```

But, would love to be able to avoid using mimic for this. Tried also to play with mox library and `Swoosh.Adapter` behaviour but it did not work.

Any pointers?
Thank you for your time!

**Comment by princemaple** [comment]
You can test it the same way we do. Make your adapter read url from config, use bypass to spin up a test server and provide the url to your adapter. Your email request hits the bypass server and you can do whatever you want there. Return any kind of error.

**Comment by princemaple** [comment]
https://github.com/swoosh/swoosh/blob/main/test/swoosh/adapters/mailgun_test.exs#L14-L31

**Comment by elvanja** [comment]
Oh, nice, very nice :) Thank you!
