### ISSUE TITLE
Many warnings because Swoosh does not declare Plug as a dependency

### ISSUE THREAD

**Issue by Sinc63** [swoosh/swoosh#808]
### Describe the bug

When I include Swoosh in my application and compile dependencies I get a LOT of warnings from Swoosh. 

The first couple:
```
warning: Plug.Builder.__before_compile__/1 defined in application :plug is used by the current application but the current application does not depend on :plug. To fix this, you must do one of:

  1. If :plug is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :plug is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :plug, you may optionally skip this warning by adding [xref: [exclude: [Plug.Builder]]] to your "def project" in mix.exs

  lib/plug/mailbox_preview.ex:2: Plug.Swoosh.MailboxPreview

warning: Plug.Builder.__using__/1 defined in application :plug is used by the current application but the current application does not depend on :plug. To fix this, you must do one of:

  1. If :plug is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :plug is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :plug, you may optionally skip this warning by adding [xref: [exclude: [Plug.Builder]]] to your "def project" in mix.exs

  lib/plug/mailbox_preview.ex:17: Plug.Swoosh.MailboxPreview
```

This problem should be easily fixed by adding `{:plug, "~> 1.1"},` to the mix.exs file in the deps function.

### Steps to Reproduce the Bug or Issue

Include swoosh in my dependencies. Compile.

### Expected behavior

The app compiles without almost 300 lines of warnings.

### Platform

Erlang/OTP 24 [erts-12.3] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [jit]

Elixir 1.13.3 (compiled with Erlang/OTP 24)

**Comment by Sinc63** [comment]
Observation, which I don't think should eliminate the need to declare plug as a dependency, but I switched to Elixir 1.14.5-otp-25 and recompiled and didn't get any errors.

I still think it would make sense to declare plug as an explicit dependency.

**Comment by princemaple** [comment]
I suspect that you added `plug` or `plug_cowboy` at some point then removed it from `mix.exs`. Hence the deps are not clean. In a clean environment, either:

- you have plug or plug_cowboy in deps
- or you don't have them in mix.exs and you don't have the deps installed

You won't see the warning.

**Comment by Sinc63** [comment]
The problem is not with my deps. Swoosh is clearly dependent on Plug, but does not declare that dependency in its own mix.exs. That should be fixed, whether it is causing a compile problem or not. At least in that way it would let Swoosh control the version of Plug that is used.

**Comment by princemaple** [comment]
It is an optional dependency through plug_cowboy.
