### ISSUE TITLE
Mailgun region select

### ISSUE THREAD

**Issue by piotr-sikora-v** [swoosh/swoosh#810]
### Describe the bug

Mailgun have two endpoints... one for US, and one for EU.
Swoosh now only use US region and we cannot set EU region endpoint
US endpoint: https://api.mailgun.net/v3/
EU endpoint: https://api.eu.mailgun.net/v3

### Steps to Reproduce the Bug or Issue

Add domain to mailgun and set region to EU
Try to send message
This will report 401

### Expected behavior

Select region endpoint in config

### Platform

- OTP:
- Elixir:

**Comment by princemaple** [comment]
You can pass `base_url: "https://api.eu.mailgun.net/v3"` in, either from the adapter config, or dynamically.
