### ISSUE TITLE
Inconsistent type spec for deliver(email, config)

### ISSUE THREAD

**Issue by ryukikikie** [swoosh/swoosh#812]
### Describe the bug

Based on the type spec for [deliver(email, config)](https://hexdocs.pm/swoosh/Swoosh.Mailer.html#deliver/2), the return value type is `@spec deliver_many(list(%Swoosh.Email{}), Keyword.t()) :: {:ok, term} | {:error, term}` but it seems that the function only returns `:ok` on success when I test. Also in the same module, [the example code](https://github.com/swoosh/swoosh/blob/v1.11.6/lib/swoosh/mailer.ex#L40-L44) seems to suggest the same. 

### Steps to Reproduce the Bug or Issue

Set up the config for the Mailer and check the return value of [`deliver`](https://hexdocs.pm/swoosh/Swoosh.Mailer.html#deliver/2) func.

### Expected behavior

Put the correct type spec for `deliver` func.

### Platform

- OTP:
- Elixir:

**Comment by princemaple** [comment]
https://github.com/swoosh/swoosh/blob/main/lib/swoosh/adapters/brevo.ex#L77-L88

All adapters return `{:ok, term} | {:error, term}`. The doc is wrong.

**Comment by ryukikikie** [comment]
@princemaple Thanks for the quick fix. My app still returns :ok only, I will look into it.

**Comment by princemaple** [comment]
Which adapter is used?
