### ISSUE TITLE
Embedding images in the mail

### ISSUE THREAD

**Issue by Darshan2003** [swoosh/swoosh#816]
### Describe the bug

I want to embed images in my mail. Facing issues with it, any help or guidance would be appreciated

### Steps to Reproduce the Bug or Issue

What are these Images about?
These images are graphs of some statistical data, these graphs are generated with the help of [Contex](https://hexdocs.pm/contex/Contex.html). 

The graphs generated by Contex are in SVG form, so firstly my approach was to send the HTML mail with the SVG code directly.

But it turns out that the majority of Email clients don't support SVG

The second approach was to convert this SVG into PNG then into base64 string and place it in `img` tag. It was working fine in the local Swoosh mailbox, But in the production, the images weren't getting displayed (seems like the base64 way of displaying images was also blocked)

### Expected behavior

The final approach was to use **inline** attachments of Swoosh and send the PNG. 

It is working exactly as Expected in the local
![image](https://github.com/swoosh/swoosh/assets/69385930/5f0cb351-5fc7-4cd7-9094-78635f5532cb)

But there is a weird bug in the production 

![image](https://github.com/swoosh/swoosh/assets/69385930/5fef7940-d931-4dbf-8661-0a61cc83d0b2)

There are no labels or legends in the image 
How could only the labels get removed as I'm sending the graph as PNG ?

This is my code snippet:

 ```
defp add_body(mail, body, false), do: text_body(mail, body)
  defp add_body(mail, body, true), do: html_body(mail, body)

  defp inline_attachments(mail, opts) do
    Enum.reduce([:contacts, :conversations, :optin, :messages], mail, fn key, acc ->
      case Keyword.get(opts, key) do
        nil -> acc
        data -> attachment(acc, create_attachment(data, key))
      end
    end)
  end

  defp create_attachment(data, key) do
    Swoosh.Attachment.new({:data, data},
      filename: "#{key}.png",
      content_type: "image/png",
      type: :inline
    )
  end
```

```
def send_mail() do
  ...internal logic
  ...
  new()
    |> to(send_to)
    |> from(from_email)
    |> cc(in_cc)
    |> subject(subject)
    |> add_body(body, is_html)
    |> inline_attachments(opts)
end
```

### Platform

- OTP: 25
- Elixir: 1.14.5

**Comment by princemaple** [comment]
I'd be surprised if swoosh had anything to do with the bug. Check your production data, see if the shape has any difference. Maybe something is nil when it shouldn't be. And check your graph lib, maybe it is on a different version from the one you're using locally.

**Comment by Darshan2003** [comment]
Tested in the production with the same data and version that of local, it is working in local but breaks in the production.

**Comment by princemaple** [comment]
My suggestion is, create an endpoint to show the generated PNG files. This way you don't go through email provider or swoosh. We don't have any code that does anything on images. There is no way swoosh modifies your images.
