### ISSUE TITLE
Does swoosh support connection pooling?

### ISSUE THREAD

**Issue by yasoob** [swoosh/swoosh#821]
**Is your feature request related to a problem? Please describe.**

When sending a huge number of emails it is preferable to keep the smtp connection open and send multiple emails over the same connection. I wasn’t able to figure out if Swoosh Suports connection pooling. Can you guys please share if it does?

**Is your feature request related to a specific adapter? Please specify.**

SMTP

**Describe the solution you'd like**

It should be possible to use a pool of smtp connections for increased throughout

**Describe alternatives you've considered**

**Additional context**

**Comment by princemaple** [comment]
You can config finch to pool http connections for you. However, we don't handle SMTP pooling.

**Comment by princemaple** [comment]
https://github.com/gen-smtp/gen_smtp/issues/67
