### ISSUE TITLE
Multiple reply_to addresses for Mailgun

### ISSUE THREAD

**Issue by ghostdsb** [swoosh/swoosh#849]
**Is your feature request related to a problem? Please describe.**
There should be a way to specify multiple addresses for reply_to.

**Is your feature request related to a specific adapter? Please specify.**
Mailgun

**Describe the solution you'd like**
As per discussions in this [issue](https://github.com/swoosh/swoosh/issues/738), adding `[mailbox()]` to reply_to type and handling `is_list` in adapter should do the trick

**Describe alternatives you've considered**
I considered setting the header value, but then we would have Reply-to(from default value) and Reply-To(from header) 

![swoosh](https://github.com/swoosh/swoosh/assets/20119474/dcda8727-b198-4a2b-a099-155019bc0536)

I do have a working PR ready that I used in a project, sending it for further discussion.

**Comment by ghostdsb** [comment]
PR link mentioned above https://github.com/swoosh/swoosh/pull/850

**Comment by princemaple** [comment]
Where does the default value come from? Is it from your application code? Adaptor code doesn't add anything if it's nil.

The pr looks pretty good though. I'll take a deeper dive soon.

**Comment by ghostdsb** [comment]
Yes, you are right. I was confused by seeing `Reply-to` and `Reply-To` in the preview. I see that a `Reply-To` header does not overwrite `Reply-to`.
