### ISSUE TITLE
Return failure list when using /email/send API in SMTP2GO Adapter

### ISSUE THREAD

**Issue by dl-00-e8** [swoosh/swoosh#868]
**Is your feature request related to a problem? Please describe.**

When calling SMTP2GO's /email/send API, the response body returns a count of succeeded and failed and list of failed data along with the email_id. The deliver method of [this file](https://github.com/swoosh/swoosh/blob/main/lib/swoosh/adapters/smtp2go.ex) return only the email_id. I want to change this to return the entire response body so that I can perform different logic on failed email information.

**Is your feature request related to a specific adapter? Please specify.**

This is related to SMTP2GO.

**Describe the solution you'd like**

Returning the entire response body when calling SMTP2GO's /email/send API

**Describe alternatives you've considered**

There is no alternatives without building new adapter myself.

**Additional context**

Response example about /email/send API in SMTP2GO
<img width="1471" alt="image" src="https://github.com/swoosh/swoosh/assets/76556999/da700808-05af-4ddd-a18c-744e418dc31d">

**Comment by princemaple** [comment]
Resolved in v1.15.3
