### ISSUE TITLE
alternative SMTP adapter

### ISSUE THREAD

**Issue by ruslandoga** [swoosh/swoosh#869]
👋

Just checking if there is any interest in an alternative SMTP adapter which doesn't use `gen_smtp`: http://github.com/ruslandoga/swoosh_mua

Instead of `gen_smtp` it uses a minimal Mint-like SMTP client http://github.com/ruslandoga/mua

I believe some of the TLS issues in OTP-26 would be resolved that way.

**Comment by princemaple** [comment]
This actually looks interesting enough. Yeah I'd love to see the PR. One tiny thing, I prefer the `@impl true` to be removed, as they add `@doc false` automatically and make the functions hard to find on hex docs. I don't intend to write `@doc` for every function for every adapter so I fallback to not having @impl true`
