### ISSUE TITLE
Error on send email with attachment

### ISSUE THREAD

**Issue by azharmalik3** [swoosh/swoosh#889]
### Describe the bug

After the update from 1.15.3 to 1.16.3, I am getting errors using the Mailgun adapter when include the email attachments:
```
(UndefinedFunctionError) function Multipart.Part.file_content_field/5 is undefined or private\\n    (multipart 0.4.0) Multipart.Part.file_content_field(\\\"Evercam Dublin Office I--2024-Mar-28--22:46.jpg\\\", <<255, 216, 255, 224, 0, 16, 74, 70, 73, 70, 0, 1, 2, 0, 0, 1, 0, 1, 0, 0, 255, 254, 0, 16, 76, 97, 118, , 21, 24, ...>>, \\\"attachment\\\", [], [content_type: \\\"image/jpeg\\\"])
```

### Steps to Reproduce the Bug or Issue

Easy to reproduce this error. Just include attachments.

### Platform

- OTP: 24.0
- Elixir: 1.14.0

### Additional context

We just downgraded `swoosh` to 1.15.3 it started working again. It means this error especially happened after rewriting multipart in 1.16.1

**Comment by princemaple** [comment]
Now it needs a new dependency, `:multipart`

**Comment by princemaple** [comment]
For mailgun.

**Comment by azharmalik3** [comment]
I already included `:multipart` dependency and got the same error.

Is there anything I need to change in my code?

![image](https://github.com/swoosh/swoosh/assets/6176136/d76056c1-84b4-4672-9b54-cb2e71c3de1e)

I don't see any required changes in the doc.

**Comment by princemaple** [comment]
No change in code needed. Please try removing deps and _build directories.

**Comment by azharmalik3** [comment]
Same error

```
(UndefinedFunctionError) function Multipart.Part.file_content_field/5 is undefined or private
```

**Comment by princemaple** [comment]
Hmm, I'm currently travelling with very bad internet. I'll have to look into it next week after Easter break. @krainboltgreene would you be interested in having a look?

**Comment by krainboltgreene** [comment]
We should have a test case for this. I'll look into it today.

**Comment by princemaple** [comment]
Hi @azharmalik3 , I just manually tested this case `|> attachment`, with `Swoosh.Attachment.new`, with `{:data, ...}` and `:inline`. It sent without a problem for me. Could you provide a minimal reproduction repo for this issue? Thanks.

**Comment by krainboltgreene** [comment]
Okay so the function definition is https://hexdocs.pm/multipart/Multipart.Part.html#file_content_field/5 and the call site is https://github.com/swoosh/swoosh/blob/main/lib/swoosh/adapters/mailgun.ex#L195-L203 and the error details:

```
Multipart.Part.file_content_field(
  \\\"Evercam Dublin Office I--2024-Mar-28--22:46.jpg\\\",
  <<255, 216, 255, 224, 0, 16, 74, 70, 73, 70, 0, 1, 2, 0, 0, 1, 0, 1, 0, 0, 255, 254, 0, 16, 76, 97, 118, , 21, 24, ...>>,
  \\\"attachment\\\",
  [],
  [content_type: \\\"image/jpeg\\\"]
)
```

So this directly matches the signature of the function both in arguments and type.

The only way this happens is if your complication is incorrect somehow.
