### ISSUE TITLE
Support for Erlang 19

### ISSUE THREAD

**Issue by JustMikey** [swoosh/swoosh#89]
Swoosh depends on the `gen_smtp` package version `0.10.0` which uses, apparently, now old spec format and thus I can't compile it using elixir 1.3.0. I am wondering if we can bump the `gen_smtp` version to `0.11.0`  and release a new minor version, 3.0.1?

**Comment by stevedomin** [comment]
Hi @JustMikey, I will take care of that today.

**Comment by JustMikey** [comment]
@stevedomin Thank you.

**Comment by nicksanders** [comment]
@JustMikey you can add the line below to your mix file as temporary fix

{:gen_smtp, "~> 0.11.0", override: true},

**Comment by JustMikey** [comment]
@nicksanders Yeah I know, thanks.

**Comment by stevedomin** [comment]
Support for Erlang 19.0 has landed in master

**Comment by JustMikey** [comment]
Awesome!
