### ISSUE TITLE
Finish experimental assertions module

### ISSUE THREAD

**Issue by princemaple** [swoosh/swoosh#909]
Bring `Swoosh.X.TestAssertions` on par with `Swoosh.TestAssertions`

**Comment by edgarlatorre** [comment]
I'd like to help here, can you give a bit more context about what needs to be done?

**Comment by princemaple** [comment]
Thanks for offering to help 😃 

We basically need to go through every function (macro) there is the non experimental one, and make sure the X one can do the same but with a less magical function. The existing implementation can serve as a good implementation guide. AFAIK there are a few of them missing.

**Comment by edgarlatorre** [comment]
Okay, let me try to do this then. Thanks

**Comment by princemaple** [comment]
cheers!
