### ISSUE TITLE
The AWS SES region can't be overriden using the ExAwsSES adapter

### ISSUE THREAD

**Issue by hellomika** [swoosh/swoosh#913]
### Describe the bug

The region setting of the ExAws config may be set to a region without support for SES. In this case, this setting should be overridden when calling `Swoosh.Adapters.ExAwsAmazonSES.deliver/2`.

Unfortunately the override is ignored leading to a crash:
```
** (RuntimeError) ses not supported in region <unsupported-region> for partition aws
```

### Steps to Reproduce the Bug or Issue

1. Configured `ex_aws` with a region without support for SES, for example `ap-east-1`
2. Build an email
3. Attempt to deliver the email with a region override, for example `Swoosh.Adapters.ExAwsAmazonSES.deliver(email, region: "us-east-1")`
4. Observe a runtime error: `** (RuntimeError) ses not supported in region ap-east-1 for partition aws`

### Expected behavior

The region override should be accepted and, if the region supports SES, the email should be sent (assuming valid credentials).

### Platform

- OTP: 26
- Elixir: 1.16.2

**Comment by princemaple** [comment]
Huh, weird. I thought the adapter code handled exactly that case.

**Comment by princemaple** [comment]
Cheers. I'll review it today. (AEST)
