### ISSUE TITLE
Dialyzer reports unknown function

### ISSUE THREAD

**Issue by Munksgaard** [swoosh/swoosh#922]
### Describe the bug

When running `mix dialyzer` I get the following error:

```
lib/foo_web/router.ex:52:unknown_function
Function Plug.Swoosh.MailboxPreview.init/1 does not exist.
________________________________________________________________________________
done (warnings were emitted)
Halting VM with exit status 2
error: Recipe `dialyzer` failed on line 17 with exit code 2
```

### Steps to Reproduce the Bug or Issue

Install dialyzer and add mailbox preview to router.ex:

```elixir
  if Application.compile_env(:foo, :dev_routes) do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
```

### Platform

- OTP: 25
- Elixir: 1.16.2

### Additional context

I'm using dialyxir 1.4.3 and swoosh 1.11.4.

**Comment by princemaple** [comment]
Hi, could you first try and update to latest version? `1.16.9`

**Comment by Munksgaard** [comment]
That seems to work, weird. I haven't had that issue before using 1.11.4, but I guess it was time to upgrade anyway.

Thanks for the quick response!
