### ISSUE TITLE
Mailgun including custom variables

### ISSUE THREAD

**Issue by dighjd12** [swoosh/swoosh#93]
Hello all! 

I'm using Swoosh right now with the Mailgun adapter. One of the features in Mailgun is including custom variables in the params of the post request, and the variables will be later included in mailgun event webhooks, and allow us to identify mails using our variables. 

More details: https://documentation.mailgun.com/user_manual.html#attaching-data-to-messages

From looking at prepare_body methods, swoosh mailgun adapter doesn't seem to allow including other params like the custom variables (let me know if this is not the case!!). I would like to make pull request to add this functionality in the mailgun adapter. I already read guidelines for contributing but since I have never contributed to open source codes before, I want to check if this is a good/valid feature to add. :) Please let me know if I should go ahead and add codes!

**Comment by stevedomin** [comment]
hi @dighjd12 

This is definitely something we should support. We can stick these in the `provider_options` field on `%Swoosh.Email{}`.

Let us know if you need any help with the code.

**Comment by dighjd12** [comment]
@stevedomin great! I'll go ahead and work on it 👍

**Comment by princemaple** [comment]
:tada: #94
