### ISSUE TITLE
MsGraph Adapter failing to find gen_smtp dependency

### ISSUE THREAD

**Issue by LetThereBeDwight** [swoosh/swoosh#954]
### Describe the bug

I’m attempting to utilize the new MSGraph adapter and it mostly works - the one issue I’m having is that even though I’ve got gen_smtp in my deps (and in the lock), I’m getting the error:

```
[error] The following dependencies are required to use Swoosh.Adapters.MsGraph:

- :gen_smtp
```

The error is triggered by this bit of code:

```
  @spec validate_dependency([module | {atom, module}]) ::
          :ok | {:error, [module | {:atom | module}]}
  def validate_dependency(required_deps) do
    if Enum.all?(required_deps, fn
         {_lib, module} -> Code.ensure_loaded?(module)
         module -> Code.ensure_loaded?(module)
       end),
       do: :ok,
       else: {:error, required_deps}
  end
```
 
Unless I go and manually update the required dependencies for that adapter to be [gen_smtp: :gen_smtp_client] as with other adapters that have any bit of similar dependency requirement, it fails with an error (with the change, everything seems to work fine).

So what I’m kinda looking for help here on is twofold:

1) Assuming the dependency definition is correct, how do I get it to pick up gen_smtp?

2) Is the dependency definition correct? It likely only requires the client, but I’m not super aware of the internals here of how this adapter is referencing it. Even further, does this requirement make any sense at all when using the MS Graph API, since it’s really just backed by a Rest API?

Thanks for any insight someone might have on either of these!

### Steps to Reproduce the Bug or Issue

Brought the MsGraph adapter into an umbrella project, with gen_smtp as a dependency, and tried to use it.

### Platform

- OTP: 26
- Elixir: elixir 1.16.1

**Comment by princemaple** [comment]
Probably just missing a recompilation. Could just be fixed with deleting the build dir.

**Comment by LetThereBeDwight** [comment]
> Probably just missing a recompilation. Could just be fixed with deleting the build dir.

Dumped my deps and build folders and rebuilt and no luck

**Comment by LetThereBeDwight** [comment]
@justindotpub any chance you've got any thoughts here on how I can get around it, or the validity of the dependency?

**Comment by justindotpub** [comment]
Hey @LetThereBeDwight.  I'm not sure how this worked before (and I'm not using it anymore) but it looks like we need to change https://github.com/swoosh/swoosh/blob/f01ad3603924b80562aebf421489038cf3bf9ffd/lib/swoosh/adapters/ms_graph.ex#L37 to be like https://github.com/swoosh/swoosh/blob/f01ad3603924b80562aebf421489038cf3bf9ffd/lib/swoosh/adapters/proton_bridge.ex#L49 instead.  It has to do with how `:gen_smtp` is technically composed of `:gen_smtp_client` and `:gen_smtp_server` and `Code.ensure_loaded?(:gen_smtp)` will return false.

**Comment by LetThereBeDwight** [comment]
> Hey @LetThereBeDwight. I'm not sure how this worked before (and I'm not using it anymore) but it looks like we need to change
> 
> https://github.com/swoosh/swoosh/blob/f01ad3603924b80562aebf421489038cf3bf9ffd/lib/swoosh/adapters/ms_graph.ex#L37
> 
> to be like
> https://github.com/swoosh/swoosh/blob/f01ad3603924b80562aebf421489038cf3bf9ffd/lib/swoosh/adapters/proton_bridge.ex#L49
> 
> instead. It has to do with how `:gen_smtp` is technically composed of `:gen_smtp_client` and `:gen_smtp_server` and `Code.ensure_loaded?(:gen_smtp)` will return false.

Yea that's what I've done in my local build to just play around - glad to have your input on it though to make sure I wasn't missing some strong dependency on like, server or something haha. I'll make a PR here about it.
