### ISSUE TITLE
Can't preview emails in `Swoosh.Adapters.Local`

### ISSUE THREAD

**Issue by sobolevn** [swoosh/swoosh#96]
Here's my setup:

`config.exs`:

```elixir
config :elixir_lang_moscow, ElixirLangMoscow.Mailer,
  adapter: Swoosh.Adapters.Local
```

`router.ex`: 

```elixir
  if Mix.env == :dev do
    scope "/dev" do
      pipe_through [:browser]
      forward "/mailbox", Plug.Swoosh.MailboxPreview, [base_path: "/dev/mailbox"]
    end
  end
```

`lib/mailer.ex`:

```elixir
defmodule ElixirLangMoscow.Mailer do
  use Swoosh.Mailer, otp_app: :elixir_lang_moscow
end
```

Here's what it looks like: 
<img width="1020" alt="2016-07-25 15 51 23" src="https://cloud.githubusercontent.com/assets/4660275/17102027/3bac8366-5280-11e6-9183-bfe62eecdc9a.png">

When sending an email via `ElixirLangMoscow.Mailer.deliver/2` it returns something like: `{:ok, %{id: "3d96e237f56230a27ba9953688646530"}}` and nothing happens.

My env:

```
Erlang/OTP 19 [erts-8.0.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.3.2)
```

```
"phoenix": {:hex, :phoenix, "1.1.6", "7bf19002669c8f692f5a9c8d30dab7b49f3dc56228d5bde92a12fb426b4783c2", [:mix], [{:poison, "~> 1.5 or ~> 2.0", [hex: :poison, optional: false]}, {:plug, "~> 1.0", [hex: :plug, optional: false]}, {:cowboy, "~> 1.0", [hex: :cowboy, optional: true]}]},
```

```
"swoosh": {:hex, :swoosh, "0.4.0", "2e1c90ba80146b4ce79923e7467c0ebf10dc6cf8933f98161fa12dd5ce848928", [:mix], [{:plug, "~> 1.1", [hex: :plug, optional: true]}, {:cowboy, "~> 1.0.0", [hex: :cowboy, optional: true]}, {:gen_smtp, "~> 0.11", [hex: :gen_smtp, optional: false]}, {:poison, "~> 1.5 or ~> 2.0", [hex: :poison, optional: false]}, {:httpoison, "~> 0.8", [hex: :httpoison, optional: false]}]},
```

**Comment by stevedomin** [comment]
hi @sobolevn, do you not see any emails if you reload the page?

**Comment by sobolevn** [comment]
No, still no result for me.

**Comment by stevedomin** [comment]
That is really strange. What's the result of running this command in your IEx console: 

`Swoosh.Adapters.Local.Storage.Memory.all()`

**Comment by sobolevn** [comment]
Output:

```
iex(3)> Emails.create_and_send(:registration_confirmation, reg, :sync)         
[debug] SELECT e0."id", e0."name", e0."location", e0."time_at", e0."uid", e0."registration_link", e0."max_registrations", e0."inserted_at", e0."updated_at" FROM "events" AS e0 WHERE (e0."id" IN ($1)) [1] OK query=1.0ms
{:ok, %{id: "6c101a0443a4a6df12189a0e1c351dca"}}
iex(4)> Swoosh.Adapters.Local.Storage.Memory.all()
[%Swoosh.Email{assigns: %{layout: {ElixirLangMoscow.LayoutView, "email.html"},
    registration: %ElixirLangMoscow.Registration{__meta__: #Ecto.Schema.Metadata<:loaded>,
     active: true, barcode: "1000568579559", code: "56857955",
     company: "wemake.services", email: "mail@sobolevn.me",
     event: %ElixirLangMoscow.Event{__meta__: #Ecto.Schema.Metadata<:loaded>,
      event_speakers: #Ecto.Association.NotLoaded<association :event_speakers is not loaded>,
      id: 1, inserted_at: #Ecto.DateTime<2016-07-23T15:57:06Z>,
      location: "Moscow", max_registrations: 200, name: "Test",
      registration_link: "https://welcome.timepad.ru/",
      registrations: #Ecto.Association.NotLoaded<association :registrations is not loaded>,
      speakers: #Ecto.Association.NotLoaded<association :speakers is not loaded>,
      time_at: #Ecto.DateTime<2016-09-01T00:00:00Z>, uid: "355507",
      updated_at: #Ecto.DateTime<2016-07-23T15:57:06Z>}, event_id: 1,
     first_name: "Никита", id: 1,
     inserted_at: #Ecto.DateTime<2016-07-23T16:02:49Z>,
     last_name: "Соболев", uid: "9029115:56857955",
     updated_at: #Ecto.DateTime<2016-07-23T16:02:49Z>}}, attachments: nil,
  bcc: [], cc: [], from: {"Elixir Moscow Team", "no-reply@elixir-lang.moscow"},
  headers: %{"Message-ID" => "6c101a0443a4a6df12189a0e1c351dca"},
  html_body: "<html>\n  <head>\n    <title>Your registration is completed</title>\n  </head>\n  <body>\n    <h1>Your registration is completed</h1>\n\n<p>\n  Thanks, Никита Соболев!\n  See you on 2016-09-01 00:00:00.\n\n  Please, have your ID with you.\n</p>\n\n  </body>\n</html>\n",
  private: %{phoenix_layout: {ElixirLangMoscow.LayoutView, :email},
    phoenix_template: "registration_confirmation.html",
    phoenix_view: ElixirLangMoscow.EmailView}, provider_options: %{},
  reply_to: nil, subject: "Your registration is completed", text_body: nil,
  to: [{"", "mail@sobolevn.me"}]}]
```

**Comment by sobolevn** [comment]
Hmm, deleting all the stuff inside `_build/` and rebuilding solved the issue:
<img width="1102" alt="2016-07-25 16 56 51" src="https://cloud.githubusercontent.com/assets/4660275/17103829/ea5e1458-5288-11e6-9822-15a4c9bf7854.png">

Thanks for the quick help.

**Comment by stevedomin** [comment]
Really weird, glad to hear it's working now.

**Comment by axelclark** [comment]
I'm running into a similar problem.  I tried deleting the stuff within `_build` but that didn't fix it.  Here is my setup:

`config/dev.exs`
```
config :email_swoosh, EmailSwoosh.Mailer,
  adapter: Swoosh.Adapters.Local
```

`lib/email_swoosh/mailer.ex`
```
defmodule EmailSwoosh.Mailer do
  use Swoosh.Mailer, otp_app: :email_swoosh
end
```

I'm starting the mailbox server like this:
```
[email_swoosh] (master) $ mix swoosh.mailbox.server
[info] Running Swoosh mailbox preview server with Cowboy using http on port 4000
```

Then I'm sending a test email through iex like this:
```
iex(1)> email = EmailSwoosh.UserEmail.welcome     
%Swoosh.Email{assigns: %{}, attachments: nil, bcc: [], cc: [],
 from: {"Dr B Banner", "hulk@smash.com"}, headers: %{},
 html_body: "<h1>Hello Axel</h1>", private: %{}, provider_options: %{},
 reply_to: nil, subject: "Hello, Avengers!", text_body: "Hello Axel",
 to: [{"Axel", "axelclark@example.com"}]}

iex(2)> EmailSwoosh.Mailer.deliver(email)         
{:ok, %{id: "a31c5fa616818e2ceb127bf7bda33297"}}

iex(3)> Swoosh.Adapters.Local.Storage.Memory.all()
[%Swoosh.Email{assigns: %{}, attachments: nil, bcc: [], cc: [],
  from: {"Dr B Banner", "hulk@smash.com"},
  headers: %{"Message-ID" => "a31c5fa616818e2ceb127bf7bda33297"},
  html_body: "<h1>Hello Axel</h1>", private: %{}, provider_options: %{},
  reply_to: nil, subject: "Hello, Avengers!", text_body: "Hello Axel",
  to: [{"Axel", "axelclark@example.com"}]}]
```

When I visit `http://localhost:4000/`, I get the message inbox, but it says "Empty mailbox..."  I tried reloading, but it still shows empty.

**Comment by stevedomin** [comment]
@axelclark apologies, only saw this now. Is it still an issue?

**Comment by alg** [comment]
@axelclark You start your server with `mix`, then start another app when going into IEX session. In order for this to work you either need to connect to a running app, or to start it with `iex -S mix swoosh.mailbox.server` instead of pure `mix ...`. It will give you the console and start the app at the same time.

**Comment by donileo** [comment]
I'm currently having this issue.

**Comment by princemaple** [comment]
@donileo We are going to need more information than that :) what have you tried?

**Comment by donileo** [comment]
@princemaple Hey Sorry. I was just about to add some more information. So I pretty much have the same config as mentioned by the original op

```
config/config.exs:
-----

config :wink, WinkWeb.Mailer, adapter: Swoosh.Adapters.Local
config :swoosh, preview_port: 4001

lib/wink_web/mailer.ex:
---
defmodule WinkWeb.Mailer do
  use Swoosh.Mailer, otp_app: :wink
end
```

Sending of a test email via deliver generates a valid response via IO.inspect so I know the email is valid:

```
{:ok, %{id: "5a2c580995af6372615e07453d757731"}}
```

Some more proof that the email is valid is that if I try not to do ` mix swoosh.mailbox.server ` and instead go via invoking a Plug via my Phoenix Router I see the emails being populated correctly in the preview browser. I can stop here and call it a day but I want ``` mix swoosh.mailbox.server ``` to work as I dont want to add the snippet of code to my router.ex.

**Comment by princemaple** [comment]
Are you running the command alongside your phoenix app? Like, one shell running `mix phx.server` and the other running `mix swoosh.mailbox.server`? That is not going to work. For it to work within the same process running phoenix, you can put in your `config/dev.exs`:

```elixir
config :swoosh, serve_mailbox: true, preview_port: 4001
```

This will make it run the swoosh mailbox server while you do `mix phx.server`

**Comment by donileo** [comment]
@princemaple Thanks! That configuration option did the trick. It'd be nice if this was added to the README.

**Comment by princemaple** [comment]
Glad it worked. Care to send a PR? Or I can do it a bit later.

**Comment by donileo** [comment]
> Glad it worked. Care to send a PR? Or I can do it a bit later.

Sure thing. I'll cook up a PR.

**Comment by princemaple** [comment]
Merged. Thanks again @donileo . It's much better now.
