### ISSUE TITLE
Mua adapter doesn't report charset in header

### ISSUE THREAD

**Issue by chuckwagoncomputing** [swoosh/swoosh#964]
### Describe the bug

When sending an email that contains (e.g.) smart quotes, they aren't rendered correctly in some clients because the email doesn't contain a charset declaration. 
![image](https://github.com/user-attachments/assets/c78f4342-9759-4ec4-b860-9d0f7a9246fd)

### Steps to Reproduce the Bug or Issue

Send an email, then look at the headers.  The Content-Type declaration doesn't declare the charset.
`Content-Type: text/html`

### Expected behavior

The email body header should have
`Content-Type: text/html; charset="UTF-8"`

### Platform

- OTP: 27
- Elixir: 1.17.3

### Additional context

I'm using phoenix_swoosh, not sure if that makes any difference (or if this is ever the right place to report this)

**Comment by princemaple** [comment]
Try updating `mail` dependency. https://github.com/DockYard/elixir-mail/blob/master/CHANGELOG.md They default to `UTF-8` since 0.4.0. If this doesn't fix it, give `[ruslandoga](https://github.com/ruslandoga)` a ping.

**Comment by chuckwagoncomputing** [comment]
That fixed it, thank you very much for your time.
